"use strict";

var historyitem_ColorMod_SetName = 2001;
var historyitem_ColorMod_SetVal = 2002;
var historyitem_ColorModifiers_AddColorMod = 2003;
var historyitem_SysColor_SetId = 2004;
var historyitem_PrstColor_SetId = 2005;
var historyitem_RGBColor_SetColor = 2006;
var historyitem_SchemeColor_SetId = 2007;
var historyitem_UniColor_SetColor = 2008;
var historyitem_UniColor_SetMods = 2009;
var historyitem_SrcRect_SetLTRB = 2010;
var historyitem_BlipFill_SetRasterImageId = 2011;
var historyitem_BlipFill_SetVectorImageBin = 2012;
var historyitem_BlipFill_SetSrcRect = 2013;
var historyitem_BlipFill_SetStretch = 2014;
var historyitem_BlipFill_SetTile = 2015;
var historyitem_BlipFill_SetRotWithShape = 2016;
var historyitem_SolidFill_SetColor = 2017;
var historyitem_Gs_SetColor = 2018;
var historyitem_Gs_SetPos = 2019;
var historyitem_GradLin_SetAngle = 2020;
var historyitem_GradLin_SetScale = 2021;
var historyitem_GradPath_SetPath = 2022;
var historyitem_GradPath_SetRect = 2023;
var historyitem_GradFill_AddColor = 2024;
var historyitem_GradFill_SetLin = 2025;
var historyitem_GradFill_SetPath = 2026;
var historyitem_PathFill_SetFType = 2027;
var historyitem_PathFill_SetFgClr = 2028;
var historyitem_PathFill_SetBgClr = 2029;
var historyitem_UniFill_SetFill = 2030;
var historyitem_UniFill_SetTransparent = 2031;
var historyitem_EndArrow_SetType = 2032;
var historyitem_EndArrow_SetLen = 2033;
var historyitem_EndArrow_SetW = 2034;
var historyitem_LineJoin_SetType = 2035;
var historyitem_LineJoin_SetLimit = 2036;
var historyitem_Ln_SetFill = 2037;
var historyitem_Ln_SetPrstDash = 2038;
var historyitem_Ln_SetJoin = 2040;
var historyitem_Ln_SetHeadEnd = 2041;
var historyitem_Ln_SetTailEnd = 2042;
var historyitem_Ln_SetAlgn = 2043;
var historyitem_Ln_SetCap = 2044;
var historyitem_Ln_SetCmpd = 2046;
var historyitem_Ln_SetW = 2047;
var historyitem_DefaultShapeDefinition_SetSpPr = 2048;
var historyitem_DefaultShapeDefinition_SetBodyPr = 2049;
var historyitem_DefaultShapeDefinition_SetLstStyle = 2050;
var historyitem_DefaultShapeDefinition_SetStyle = 2051;
var historyitem_CNvPr_SetId = 2052;
var historyitem_CNvPr_SetName = 2053;
var historyitem_CNvPr_SetIsHidden = 2054;
var historyitem_NvPr_SetIsPhoto = 2055;
var historyitem_NvPr_SetUserDrawn = 2056;
var historyitem_NvPr_SetPh = 2057;
var historyitem_Ph_SetHasCustomPrompt = 2058;
var historyitem_Ph_SetIdx = 2059;
var historyitem_Ph_SetOrient = 2060;
var historyitem_Ph_SetSz = 2061;
var historyitem_Ph_SetType = 2062;
var historyitem_UniNvPr_SetCNvPr = 2063;
var historyitem_UniNvPr_SetUniPr = 2064;
var historyitem_UniNvPr_SetNvPr = 2065;
var historyitem_StyleRef_SetIdx = 2066;
var historyitem_StyleRef_SetColor = 2067;
var historyitem_FontRef_SetIdx = 2068;
var historyitem_FontRef_SetColor = 2069;
var historyitem_Chart_SetAutoTitleDeleted = 2070;
var historyitem_Chart_SetBackWall = 2071;
var historyitem_Chart_SetDispBlanksAs = 2072;
var historyitem_Chart_SetFloor = 2073;
var historyitem_Chart_SetLegend = 2074;
var historyitem_Chart_AddPivotFmt = 2075;
var historyitem_Chart_SetPlotArea = 2076;
var historyitem_Chart_SetPlotVisOnly = 2077;
var historyitem_Chart_SetShowDLblsOverMax = 2078;
var historyitem_Chart_SetSideWall = 2079;
var historyitem_Chart_SetTitle = 2080;
var historyitem_Chart_SetView3D = 2081;
var historyitem_ChartSpace_SetChart = 2082;
var historyitem_ChartSpace_SetClrMapOvr = 2083;
var historyitem_ChartSpace_SetDate1904 = 2084;
var historyitem_ChartSpace_SetExternalData = 2085;
var historyitem_ChartSpace_SetLang = 2086;
var historyitem_ChartSpace_SetPivotSource = 2087;
var historyitem_ChartSpace_SetPrintSettings = 2088;
var historyitem_ChartSpace_SetProtection = 2089;
var historyitem_ChartSpace_SetRoundedCorners = 2090;
var historyitem_ChartSpace_SetSpPr = 2091;
var historyitem_ChartSpace_SetStyle = 2092;
var historyitem_ChartSpace_SetTxPr = 2093;
var historyitem_ChartSpace_SetUserShapes = 2094;
var historyitem_Legend_SetLayout = 2095;
var historyitem_Legend_AddLegendEntry = 2096;
var historyitem_Legend_SetLegendPos = 2097;
var historyitem_Legend_SetOverlay = 2098;
var historyitem_Legend_SetSpPr = 2099;
var historyitem_Legend_SetTxPr = 2100;
var historyitem_Layout_SetH = 2101;
var historyitem_Layout_SetHMode = 2102;
var historyitem_Layout_SetLayoutTarget = 2103;
var historyitem_Layout_SetW = 2103;
var historyitem_Layout_SetWMode = 2104;
var historyitem_Layout_SetX = 2105;
var historyitem_Layout_SetXMode = 2105;
var historyitem_Layout_SetY = 2106;
var historyitem_Layout_SetYMode = 2107;
var historyitem_LegendEntry_SetDelete = 2108;
var historyitem_LegendEntry_SetIdx = 2109;
var historyitem_LegendEntry_SetTxPr = 2110;
var historyitem_PivotFmt_SetDLbl = 2110;
var historyitem_PivotFmt_SetIdx = 2111;
var historyitem_PivotFmt_SetMarker = 2112;
var historyitem_PivotFmt_SetSpPr = 2113;
var historyitem_PivotFmt_SetTxPr = 2114;
var historyitem_DLbl_SetDelete = 2115;
var historyitem_DLbl_SetDLblPos = 2116;
var historyitem_DLbl_SetIdx = 2117;
var historyitem_DLbl_SetLayout = 2118;
var historyitem_DLbl_SetNumFmt = 2119;
var historyitem_DLbl_SetSeparator = 2120;
var historyitem_DLbl_SetShowBubbleSize = 2121;
var historyitem_DLbl_SetShowCatName = 2122;
var historyitem_DLbl_SetShowLegendKey = 2123;
var historyitem_DLbl_SetShowPercent = 2124;
var historyitem_DLbl_SetShowSerName = 2125;
var historyitem_DLbl_SetShowVal = 2126;
var historyitem_DLbl_SetSpPr = 2127;
var historyitem_DLbl_SetTx = 2128;
var historyitem_DLbl_SetTxPr = 2129;
var historyitem_Marker_SetSize = 2130;
var historyitem_Marker_SetSpPr = 2131;
var historyitem_Marker_SetSymbol = 2132;
var historyitem_PlotArea_AddChart  = 2133;
var historyitem_PlotArea_SetCatAx  = 2134;
var historyitem_PlotArea_SetDateAx = 2135;
var historyitem_PlotArea_SetDTable = 2136;
var historyitem_PlotArea_SetLayout = 2137;
var historyitem_PlotArea_SetSerAx  = 2138;
var historyitem_PlotArea_SetSpPr  = 2139;
var historyitem_PlotArea_SetValAx = 2140;
var historyitem_PlotArea_AddAxis = 2141;
var historyitem_PlotArea_RemoveChart = 2142;
var historyitem_PlotArea_RemoveAxis = 2143;
var historyitem_Axis_SetType               = 2141;
var historyitem_Axis_SetAuto               = 2142;
var historyitem_Axis_SetAxId               = 2143;
var historyitem_Axis_SetAxPos              = 2144;
var historyitem_Axis_SetBaseTimeUnit       = 2145;
var historyitem_Axis_SetCrossAx            = 2146;
var historyitem_Axis_SetCrossBetween       = 2147;
var historyitem_Axis_SetCrosses            = 2148;
var historyitem_Axis_SetCrossesAt          = 2149;
var historyitem_Axis_SetDelete             = 2150;
var historyitem_Axis_SetDispUnits          = 2151;
var historyitem_Axis_SetLblAlgn            = 2152;
var historyitem_Axis_SetLblOffset          = 2153;
var historyitem_Axis_SetMajorGridlines     = 2154;
var historyitem_Axis_SetMajorTickMark      = 2155;
var historyitem_Axis_SetMajorTimeUnit      = 2156;
var historyitem_Axis_SetMajorUnit          = 2157;
var historyitem_Axis_SetMinorGridlines      = 2158;
var historyitem_Axis_SetMinorTickMark       = 2159;
var historyitem_Axis_SetMinorTimeUnit      = 2160;
var historyitem_Axis_SetMinorUnit          = 2161;
var historyitem_Axis_SetNoMultiLvlLbl      = 2162;
var historyitem_Axis_SetNumFmt             = 2163;
var historyitem_Axis_SetScaling            = 2164;
var historyitem_Axis_SetSpPr               = 2165;
var historyitem_Axis_SetTickLblPos         = 2166;
var historyitem_Axis_SetTickLblSkip        = 2167;
var historyitem_Axis_SetTickMarkSkip       = 2168;
var historyitem_Axis_SetTitle              = 2169;
var historyitem_Axis_SetTxPr               = 2170;
var historyitem_NumFmt_SetFormatCode = 2171;
var historyitem_NumFmt_SetSourceLinked = 2172;
var historyitem_Scaling_SetLogBase     = 2173;
var historyitem_Scaling_SetMax         = 2174;
var historyitem_Scaling_SetMin         = 2175;
var historyitem_Scaling_SetOrientation = 2176;
var historyitem_DTable_SetShowHorzBorder = 2177;
var historyitem_DTable_SetShowKeys       = 2178;
var historyitem_DTable_SetShowOutline    = 2179;
var historyitem_DTable_SetShowVertBorder = 2180;
var historyitem_DTable_SetSpPr = 2181;
var historyitem_DTable_SetTxPr = 2182;
var historyitem_LineChart_AddAxId       = 2183;
var historyitem_LineChart_SetDLbls      = 2184;
var historyitem_LineChart_SetDropLines  = 2185;
var historyitem_LineChart_SetGrouping   = 2186;
var historyitem_LineChart_SetHiLowLines = 2187;
var historyitem_LineChart_SetMarker     = 2188;
var historyitem_LineChart_AddSer        = 2189;
var historyitem_LineChart_SetSmooth     = 2190;
var historyitem_LineChart_SetUpDownBars = 2191;
var historyitem_LineChart_SetVaryColors = 2192;
var historyitem_DLbls_SetDelete          = 2193;
var historyitem_DLbls_SetDLbl            = 2194;
var historyitem_DLbls_SetDLblPos         = 2195;
var historyitem_DLbls_SetLeaderLines     = 2196;
var historyitem_DLbls_SetNumFmt          = 2197;
var historyitem_DLbls_SetSeparator       = 2198;
var historyitem_DLbls_SetShowBubbleSize  = 2199;
var historyitem_DLbls_SetShowCatName     = 2200;
var historyitem_DLbls_SetShowLeaderLines = 2201;
var historyitem_DLbls_SetShowLegendKey   = 2202;
var historyitem_DLbls_SetShowPercent     = 2203;
var historyitem_DLbls_SetShowSerName     = 2204;
var historyitem_DLbls_SetShowVal         = 2205;
var historyitem_DLbls_SetSpPr            = 2206;
var historyitem_DLbls_SetTxPr            = 2207;
var historyitem_UpDownBars_SetDownBars   = 2208;
var historyitem_UpDownBars_SetGapWidth   = 2209;
var historyitem_UpDownBars_SetUpBars     = 2210;
var historyitem_BarChart_AddAxId        = 2211;
var historyitem_BarChart_SetBarDir      = 2212;
var historyitem_BarChart_SetDLbls       = 2213;
var historyitem_BarChart_SetGapWidth    = 2214;
var historyitem_BarChart_SetGrouping    = 2215;
var historyitem_BarChart_SetOverlap     = 2216;
var historyitem_BarChart_AddSer         = 2217;
var historyitem_BarChart_SetSerLines    = 2218;
var historyitem_BarChart_SetVaryColors  = 2219;
var historyitem_BubbleChart_AddAxId            = 2220;
var historyitem_BubbleChart_SetBubble3D        = 2221;
var historyitem_BubbleChart_SetBubbleScale     = 2222;
var historyitem_BubbleChart_SetDLbls           = 2223;
var historyitem_BubbleChart_AddSerie           = 2224;
var historyitem_BubbleChart_SetShowNegBubbles  = 2225;
var historyitem_BubbleChart_SetSizeRepresents  = 2226;
var historyitem_BubbleChart_SetVaryColors      = 2227;
var historyitem_DoughnutChart_SetDLbls      = 2228;
var historyitem_DoughnutChart_SetFirstSliceAng      = 2229;
var historyitem_DoughnutChart_SetHoleSize      = 2230;
var historyitem_DoughnutChart_AddSer     = 2231;
var historyitem_DoughnutChart_SetVaryColor      = 2232;
var historyitem_OfPieChart_AddCustSplit      = 2233;
var historyitem_OfPieChart_SetDLbls         = 2234;
var historyitem_OfPieChart_SetGapWidth      = 2235;
var historyitem_OfPieChart_SetOfPieType      = 2236;
var historyitem_OfPieChart_SetSecondPieSize      = 2237;
var historyitem_OfPieChart_AddSer           = 2238;
var historyitem_OfPieChart_SetSerLines      = 2239;
var historyitem_OfPieChart_SetSplitPos      = 2240;
var historyitem_OfPieChart_SetSplitType      = 2241;
var historyitem_OfPieChart_SetVaryColors      = 2242;
var historyitem_PieChart_SetDLbls         = 2243;
var historyitem_PieChart_SetFirstSliceAng      = 2244;
var historyitem_PieChart_AddSer           = 2245;
var historyitem_PieChart_SetVaryColors      = 2246;
var historyitem_RadarChart_AddAxId        = 2247;
var historyitem_RadarChart_SetDLbls      = 2248;
var historyitem_RadarChart_SetRadarStyle = 2249;
var historyitem_RadarChart_AddSer        = 2250;
var historyitem_RadarChart_SetVaryColors = 2251;
var historyitem_ScatterChart_AddAxId        = 2247;
var historyitem_ScatterChart_SetDLbls      = 2248;
var historyitem_ScatterChart_SetScatterStyle = 2249;
var historyitem_ScatterChart_AddSer        = 2250;
var historyitem_ScatterChart_SetVaryColors = 2251;
var historyitem_StockChart_AddAxId       = 2252;
var historyitem_StockChart_SetDLbls      = 2253;
var historyitem_StockChart_SetDropLines  = 2254;
var historyitem_StockChart_SetHiLowLines = 2255;
var historyitem_StockChart_AddSer        = 2256;
var historyitem_StockChart_SetUpDownBars = 2257;
var historyitem_SurfaceChart_AddAxId = 2258;
var historyitem_SurfaceChart_AddBandFmt = 2259;
var historyitem_SurfaceChart_AddSer = 2260;
var historyitem_SurfaceChart_SetWireframe = 2261;
var historyitem_BandFmt_SetIdx = 2262;
var historyitem_BandFmt_SetSpPr = 2263;
var historyitem_AreaChart_AddAxId       = 2264;
var historyitem_AreaChart_SetDLbls      = 2265;
var historyitem_AreaChart_SetDropLines  = 2266;
var historyitem_AreaChart_SetGrouping   = 2267;
var historyitem_AreaChart_AddSer        = 2268;
var historyitem_AreaChart_SetVaryColors = 2269;
var historyitem_ScatterSer_SetDLbls                    = 2270;
var historyitem_ScatterSer_SetDPt                      = 2271;
var historyitem_ScatterSer_SetErrBars                  = 2272;
var historyitem_ScatterSer_SetIdx                      = 2273;
var historyitem_ScatterSer_SetMarker                   = 2274;
var historyitem_ScatterSer_SetOrder                    = 2275;
var historyitem_ScatterSer_SetSmooth                   = 2276;
var historyitem_ScatterSer_SetSpPr                     = 2277;
var historyitem_ScatterSer_SetTrendline                = 2278;
var historyitem_ScatterSer_SetTx                       = 2279;
var historyitem_ScatterSer_SetXVal                     = 2280;
var historyitem_ScatterSer_SetYVal                     = 2281;
var historyitem_DPt_SetBubble3D                        = 2282;
var historyitem_DPt_SetExplosion                       = 2283;
var historyitem_DPt_SetIdx                             = 2284;
var historyitem_DPt_SetInvertIfNegative                = 2285;
var historyitem_DPt_SetMarker                          = 2286;
var historyitem_DPt_SetPictureOptions                  = 2287;
var historyitem_DPt_SetSpPr                            = 2288;
var historyitem_ErrBars_SetErrBarType                  = 2289;
var historyitem_ErrBars_SetErrDir                      = 2290;
var historyitem_ErrBars_SetErrValType                  = 2291;
var historyitem_ErrBars_SetMinus                       = 2292;
var historyitem_ErrBars_SetNoEndCap                    = 2293;
var historyitem_ErrBars_SetPlus                        = 2294;
var historyitem_ErrBars_SetSpPr                        = 2295;
var historyitem_ErrBars_SetVal                         = 2296;
var historyitem_MinusPlus_SetnNumLit                   = 2297;
var historyitem_MinusPlus_SetnNumRef                   = 2298;
var historyitem_NumLit_SetFormatCode                   = 2299;
var historyitem_NumLit_AddPt                           = 2300;
var historyitem_NumLit_SetPtCount                      = 2301;
var historyitem_NumericPoint_SetFormatCode             = 2302;
var historyitem_NumericPoint_SetIdx                    = 2303;
var historyitem_NumericPoint_SetVal                    = 2304;
var historyitem_NumRef_SetF                            = 2305;
var historyitem_NumRef_SetNumCache                     = 2306;
var historyitem_Trendline_SetBackward                  = 2307;
var historyitem_Trendline_SetDispEq                    = 2308;
var historyitem_Trendline_SetDispRSqr                  = 2309;
var historyitem_Trendline_SetForward                   = 2310;
var historyitem_Trendline_SetIntercept                 = 2311;
var historyitem_Trendline_SetName                      = 2312;
var historyitem_Trendline_SetOrder                     = 2313;
var historyitem_Trendline_SetPeriod                    = 2314;
var historyitem_Trendline_SetSpPr                      = 2315;
var historyitem_Trendline_SetTrendlineLbl              = 2316;
var historyitem_Trendline_SetTrendlineType             = 2317;
var historyitem_Tx_SetStrRef                          = 2318;
var historyitem_Tx_SetVal                             = 2319;
var historyitem_StrRef_SetF                           = 2319;
var historyitem_StrRef_SetStrCache                    = 2320;
var historyitem_StrCache_AddPt                       = 2321;
var historyitem_StrCache_SetPtCount                      = 2322;
var historyitem_StrPoint_SetIdx                      = 2323;
var historyitem_StrPoint_SetVal                      = 2324;
var historyitem_XVal_SetMultiLvlStrRef                = 2325;
var historyitem_XVal_SetNumLit                        = 2326;
var historyitem_XVal_SetNumRef                        = 2327;
var historyitem_XVal_SetStrLit                        = 2328;
var historyitem_XVal_SetStrRef                        = 2329;
var historyitem_MultiLvlStrRef_SetF                    = 2330;
var historyitem_MultiLvlStrRef_SetMultiLvlStrCache     = 2331;
var historyitem_MultiLvlStrCache_SetLvl                = 2332;
var historyitem_MultiLvlStrCache_SetPtCount            = 2333;
var historyitem_StringLiteral_SetPt               = 2334;
var historyitem_StringLiteral_SetPtCount          = 2335;
var historyitem_YVal_SetNumLit                    = 2336;
var historyitem_YVal_SetNumRef                    = 2337;
var historyitem_AreaSeries_SetCat                       = 2338;
var historyitem_AreaSeries_SetDLbls                     = 2339;
var historyitem_AreaSeries_SetDPt                       = 2340;
var historyitem_AreaSeries_SetErrBars                   = 2341;
var historyitem_AreaSeries_SetIdx                       = 2342;
var historyitem_AreaSeries_SetOrder                     = 2343;
var historyitem_AreaSeries_SetPictureOptions            = 2344;
var historyitem_AreaSeries_SetSpPr                      = 2345;
var historyitem_AreaSeries_SetTrendline                 = 2346;
var historyitem_Cat_SetMultiLvlStrRef                   = 2347;
var historyitem_Cat_SetNumLit                           = 2348;
var historyitem_Cat_SetNumRef                           = 2349;
var historyitem_Cat_SetStrLit                           = 2350;
var historyitem_Cat_SetStrRef                           = 2351;
var historyitem_PictureOptions_SetApplyToEnd              = 2352;
var historyitem_PictureOptions_SetApplyToFront         = 2353;
var historyitem_PictureOptions_SetApplyToSides          = 2354;
var historyitem_PictureOptions_SetPictureFormat      = 2355;
var historyitem_PictureOptions_SetPictureStackUnit        = 2356;
var historyitem_RadarSeries_SetCat        = 2357;
var historyitem_RadarSeries_SetDLbls    = 2357;
var historyitem_RadarSeries_SetDPt     = 2358;
var historyitem_RadarSeries_SetIdx     = 2359;
var historyitem_RadarSeries_SetMarker  = 2360;
var historyitem_RadarSeries_SetOrder   = 2361;
var historyitem_RadarSeries_SetSpPr    = 2362;
var historyitem_RadarSeries_SetTx      = 2363;
var historyitem_RadarSeries_SetVal     = 2364;
var historyitem_BarSeries_SetCat                  = 2365;
var historyitem_BarSeries_SetDLbls                = 2366;
var historyitem_BarSeries_SetDPt                 = 2367;
var historyitem_BarSeries_SetErrBars              = 2368;
var historyitem_BarSeries_SetIdx                 = 2369;
var historyitem_BarSeries_SetInvertIfNegative     = 2370;
var historyitem_BarSeries_SetOrder                = 2371;
var historyitem_BarSeries_SetPictureOptions       = 2372;
var historyitem_BarSeries_SetShape                = 2373;
var historyitem_BarSeries_SetSpPr                 = 2374;
var historyitem_BarSeries_SetTrendline            = 2375;
var historyitem_BarSeries_SetTx                 = 2376;
var historyitem_BarSeries_SetVal                 = 2377;
var historyitem_LineSeries_SetCat               = 2378;
var historyitem_LineSeries_SetDLbls             = 2379;
var historyitem_LineSeries_SetDPt               = 2380;
var historyitem_LineSeries_SetErrBars           = 2381;
var historyitem_LineSeries_SetIdx               = 2382;
var historyitem_LineSeries_SetMarker            = 2383;
var historyitem_LineSeries_SetOrder             = 2384;
var historyitem_LineSeries_SetSmooth            = 2385;
var historyitem_LineSeries_SetSpPr              = 2386;
var historyitem_LineSeries_SetTrendline         = 2387;
var historyitem_LineSeries_SetTx                = 2388;
var historyitem_LineSeries_SetVal               = 2389;
var historyitem_PieSeries_SetCat                = 2390;
var historyitem_PieSeries_SetDLbls              = 2391;
var historyitem_PieSeries_SetDPt                = 2392;
var historyitem_PieSeries_SetExplosion          = 2393;
var historyitem_PieSeries_SetIdx                = 2394;
var historyitem_PieSeries_SetOrder              = 2395;
var historyitem_PieSeries_SetSpPr               = 2396;
var historyitem_PieSeries_SetTx                 = 2397;
var historyitem_PieSeries_SetVal                = 2398;
var historyitem_SurfaceSeries_SetCat            = 2399;
var historyitem_SurfaceSeries_SetIdx            = 2400;
var historyitem_SurfaceSeries_SetOrder          = 2401;
var historyitem_SurfaceSeries_SetSpPr           = 2402;
var historyitem_SurfaceSeries_SetTx             = 2403;
var historyitem_SurfaceSeries_SetVal            = 2404;
var historyitem_BubbleSeries_SetBubble3D         = 2405;
var historyitem_BubbleSeries_SetBubbleSize       = 2406;
var historyitem_BubbleSeries_SetDLbls            = 2407;
var historyitem_BubbleSeries_SetDPt              = 2408;
var historyitem_BubbleSeries_SetErrBars          = 2409;
var historyitem_BubbleSeries_SetIdx              = 2410;
var historyitem_BubbleSeries_SetInvertIfNegative = 2411;
var historyitem_BubbleSeries_SetOrder            = 2412;
var historyitem_BubbleSeries_SetSpPr             = 2413;
var historyitem_BubbleSeries_SetTrendline        = 2414;
var historyitem_BubbleSeries_SetTx               = 2415;
var historyitem_BubbleSeries_SetXVal             = 2416;
var historyitem_BubbleSeries_SetYVal             = 2417;
var historyitem_ExternalData_SetAutoUpdate       = 2418;
var historyitem_ExternalData_SetId               = 2419;
var historyitem_PivotSource_SetFmtId            = 2420;
var historyitem_PivotSource_SetName               = 2421;
var historyitem_Protection_SetChartObject         = 2422;
var historyitem_Protection_SetData                = 2423;
var historyitem_Protection_SetFormatting          = 2424;
var historyitem_Protection_SetSelection           = 2425;
var historyitem_Protection_SetUserInterface       = 2426;
var historyitem_ChartWall_SetPictureOptions       = 2427;
var historyitem_ChartWall_SetSpPr                 = 2428;
var historyitem_ChartWall_SetThickness            = 2429;
var historyitem_View3d_SetDepthPercent            = 2430;
var historyitem_View3d_SetHPercent                = 2431;
var historyitem_View3d_SetPerspective             = 2432;
var historyitem_View3d_SetRAngAx                  = 2433;
var historyitem_View3d_SetRotX                    = 2434;
var historyitem_View3d_SetRotY                    = 2435;
var historyitem_Title_SetLayout                   = 2436;
var historyitem_Title_SetOverlay                  = 2437;
var historyitem_Title_SetSpPr                     = 2438;
var historyitem_Title_SetTx                       = 2439;
var historyitem_Title_SetTxPr                     = 2440;
var historyitem_ChartText_SetRich   = 2441;
var historyitem_ChartText_SetStrRef = 2442;
var historyitem_ShapeStyle_SetLnRef   = 2443;
var historyitem_ShapeStyle_SetFillRef = 2444;
var historyitem_ShapeStyle_SetFontRef = 2445;
var historyitem_ShapeStyle_SetEffectRef = 2446;
var historyitem_Xfrm_SetOffX          = 2446;
var historyitem_Xfrm_SetOffY          = 2447;
var historyitem_Xfrm_SetExtX          = 2448;
var historyitem_Xfrm_SetExtY          = 2449;
var historyitem_Xfrm_SetChOffX        = 2450;
var historyitem_Xfrm_SetChOffY        = 2451;
var historyitem_Xfrm_SetChExtX        = 2452;
var historyitem_Xfrm_SetChExtY        = 2453;
var historyitem_Xfrm_SetFlipH         = 2454;
var historyitem_Xfrm_SetFlipV         = 2455;
var historyitem_Xfrm_SetRot           = 2456;
var historyitem_Xfrm_SetParent        = 2457;
var historyitem_SpPr_SetBwMode        = 2457;
var historyitem_SpPr_SetXfrm          = 2458;
var historyitem_SpPr_SetGeometry      = 2459;
var historyitem_SpPr_SetFill          = 2460;
var historyitem_SpPr_SetLn            = 2461;
var historyitem_SpPr_SetParent        = 2462;
var historyitem_ClrScheme_AddClr      = 2462;
var historyitem_ClrScheme_SetName     = 2463;
var historyitem_ClrMap_SetClr         = 2464;
var historyitem_ExtraClrScheme_SetClrScheme  = 2465;
var historyitem_ExtraClrScheme_SetClrMap     = 2466;
var historyitem_FontCollection_SetLatin      = 2467;
var historyitem_FontCollection_SetEA         = 2468;
var historyitem_FontCollection_SetCS         = 2469;
var historyitem_FontScheme_SetName         = 2470;
var historyitem_FontScheme_SetMajorFont         = 2471;
var historyitem_FontScheme_SetMinorFont         = 2472;
var historyitem_FormatScheme_SetName             = 2473;
var historyitem_FormatScheme_AddFillToStyleLst     = 2474;
var historyitem_FormatScheme_AddLnToStyleLst       = 2475;
var historyitem_FormatScheme_AddEffectToStyleLst   = 2476;
var historyitem_FormatScheme_AddBgFillToStyleLst   = 2477;
var historyitem_ThemeElements_SetClrScheme   = 2478;
var historyitem_ThemeElements_SetFontScheme   = 2479;
var historyitem_ThemeElements_SetFmtScheme   = 2480;
var historyitem_HF_SetDt      = 2481;
var historyitem_HF_SetFtr     = 2482;
var historyitem_HF_SetHdr     = 2483;
var historyitem_HF_SetSldNum  = 2484;
var historyitem_BgPr_SetFill  = 2485;
var historyitem_BgPr_SetShadeToTitle  = 2486;
var historyitem_BgSetBwMode   = 2487;
var historyitem_BgSetBgPr     = 2488;
var historyitem_BgSetBgRef    = 2489;
var historyitem_PrintSettingsSetHeaderFooter = 2490;
var historyitem_PrintSettingsSetPageMargins  = 2491;
var historyitem_PrintSettingsSetPageSetup    = 2492;
var historyitem_HeaderFooterChartSetAlignWithMargins = 2493;
var historyitem_HeaderFooterChartSetDifferentFirst   = 2494;
var historyitem_HeaderFooterChartSetDifferentOddEven = 2495;
var historyitem_HeaderFooterChartSetEvenFooter       = 2496;
var historyitem_HeaderFooterChartSetEvenHeader       = 2497;
var historyitem_HeaderFooterChartSetFirstFooter      = 2498;
var historyitem_HeaderFooterChartSetFirstHeader      = 2499;
var historyitem_HeaderFooterChartSetOddFooter        = 2500;
var historyitem_HeaderFooterChartSetOddHeader        = 2501;
var historyitem_PageMarginsSetB      = 2502;
var historyitem_PageMarginsSetFooter = 2503;
var historyitem_PageMarginsSetHeader = 2504;
var historyitem_PageMarginsSetL      = 2505;
var historyitem_PageMarginsSetR      = 2506;
var historyitem_PageMarginsSetT      = 2507;
var historyitem_PageSetupSetBlackAndWhite     = 2508;
var historyitem_PageSetupSetCopies            = 2509;
var historyitem_PageSetupSetDraft             = 2510;
var historyitem_PageSetupSetFirstPageNumber   = 2511;
var historyitem_PageSetupSetHorizontalDpi     = 2512;
var historyitem_PageSetupSetOrientation       = 2513;
var historyitem_PageSetupSetPaperHeight       = 2514;
var historyitem_PageSetupSetPaperSize         = 2515;
var historyitem_PageSetupSetPaperWidth        = 2516;
var historyitem_PageSetupSetUseFirstPageNumb  = 2517;
var historyitem_PageSetupSetVerticalDpi       = 2518;
var historyitem_ShapeSetNvSpPr                = 2519;
var historyitem_ShapeSetSpPr                  = 2520;
var historyitem_ShapeSetStyle                 = 2521;
var historyitem_ShapeSetTxBody                = 2522;
var historyitem_ShapeSetTextBoxContent        = 2523;
var historyitem_ShapeSetParent                = 2524;
var historyitem_ShapeSetGroup                 = 2525;
var historyitem_ShapeSetBodyPr                = 2526;
var historyitem_DispUnitsSetBuiltInUnit       = 2526;
var historyitem_DispUnitsSetCustUnit          = 2527;
var historyitem_DispUnitsSetDispUnitsLbl      = 2528;
var historyitem_GroupShapeSetNvGrpSpPr        = 2529;
var historyitem_GroupShapeSetSpPr             = 2530;
var historyitem_GroupShapeAddToSpTree           = 2531;
var historyitem_GroupShapeSetParent          = 2532;
var historyitem_GroupShapeSetGroup            = 2533;
var historyitem_GroupShapeRemoveFromSpTree    = 2534;
var historyitem_ImageShapeSetNvPicPr    = 2535;
var historyitem_ImageShapeSetSpPr     = 2536;
var historyitem_ImageShapeSetBlipFill    = 2537;
var historyitem_ImageShapeSetParent    = 2538;
var historyitem_ImageShapeSetGroup    = 2539;
var historyitem_GeometrySetParent       = 2540;
var historyitem_GeometryAddAdj          = 2541;
var historyitem_GeometryAddGuide        = 2542;
var historyitem_GeometryAddCnx          = 2543;
var historyitem_GeometryAddHandleXY     = 2544;
var historyitem_GeometryAddHandlePolar  = 2545;
var historyitem_GeometryAddPath         = 2546;
var historyitem_GeometryAddRect         = 2547;
var historyitem_GeometrySetPreset       = 2548;
var historyitem_PathSetStroke           = 2549;
var historyitem_PathSetExtrusionOk      = 2550;
var historyitem_PathSetFill             = 2551;
var historyitem_PathSetPathH            = 2552;
var historyitem_PathSetPathW            = 2553;
var historyitem_PathAddPathCommand      = 2554;
var historyitem_TextBodySetBodyPr       = 2555;
var historyitem_TextBodySetLstStyle     = 2557;
var historyitem_TextBodySetContent      = 2558;
var historyitem_TextBodySetParent       = 2559;
var historyitem_CatAxSetAuto           =  2560;
var historyitem_CatAxSetAxId           =  2561;
var historyitem_CatAxSetAxPos          =  2562;
var historyitem_CatAxSetCrossAx        =  2563;
var historyitem_CatAxSetCrosses        =  2564;
var historyitem_CatAxSetCrossesAt      =  2565;
var historyitem_CatAxSetDelete         =  2566;
var historyitem_CatAxSetExtLst         =  2567;
var historyitem_CatAxSetLblAlgn        =  2568;
var historyitem_CatAxSetLblOffset      =  2569;
var historyitem_CatAxSetMajorGridlines =  2570;
var historyitem_CatAxSetMajorTickMark  =  2571;
var historyitem_CatAxSetMinorGridlines =  2572;
var historyitem_CatAxSetMinorTickMark  =  2573;
var historyitem_CatAxSetNoMultiLvlLbl  =  2574;
var historyitem_CatAxSetNumFmt         =  2575;
var historyitem_CatAxSetScaling        =  2576;
var historyitem_CatAxSetSpPr           =  2577;
var historyitem_CatAxSetTickLblPos     =  2578;
var historyitem_CatAxSetTickLblSkip    =  2579;
var historyitem_CatAxSetTickMarkSkip   =  2580;
var historyitem_CatAxSetTitle          =  2581;
var historyitem_CatAxSetTxPr           =  2582;

var historyitem_ValAxSetAxId              = 2583;
var historyitem_ValAxSetAxPos             = 2584;
var historyitem_ValAxSetCrossAx           = 2585;
var historyitem_ValAxSetCrossBetween      = 2586;
var historyitem_ValAxSetCrosses           = 2587;
var historyitem_ValAxSetCrossesAt         = 2588;
var historyitem_ValAxSetDelete            = 2589;
var historyitem_ValAxSetDispUnits         = 2590;
var historyitem_ValAxSetExtLst            = 2591;
var historyitem_ValAxSetMajorGridlines    = 2592;
var historyitem_ValAxSetMajorTickMark     = 2593;
var historyitem_ValAxSetMajorUnit         = 2594;
var historyitem_ValAxSetMinorGridlines    = 2595;
var historyitem_ValAxSetMinorTickMark     = 2596;
var historyitem_ValAxSetMinorUnit         = 2597;
var historyitem_ValAxSetNumFmt            = 2598;
var historyitem_ValAxSetScaling           = 2599;
var historyitem_ValAxSetSpPr              = 2600;
var historyitem_ValAxSetTickLblPos        = 2601;
var historyitem_ValAxSetTitle             = 2602;
var historyitem_ValAxSetTxPr              = 2603;

var historyitem_type_ColorMod = 1001;
var historyitem_type_ColorModifiers = 1002;
var historyitem_type_SysColor = 1003;
var historyitem_type_PrstColor = 1004;
var historyitem_type_RGBColor = 1005;
var historyitem_type_SchemeColor = 1006;
var historyitem_type_UniColor = 1007;
var historyitem_type_SrcRect = 1008;
var historyitem_type_BlipFill = 1009;
var historyitem_type_SolidFill = 1010;
var historyitem_type_Gs = 1011;
var historyitem_type_GradLin = 1012;
var historyitem_type_GradPath = 1013;
var historyitem_type_GradFill = 1014;
var historyitem_type_PathFill = 1015;
var historyitem_type_NoFill = 1016;
var historyitem_type_UniFill = 1017;
var historyitem_type_EndArrow = 1018;
var historyitem_type_LineJoin = 1019;
var historyitem_type_Ln = 1020;
var historyitem_type_DefaultShapeDefinition = 1021;
var historyitem_type_CNvPr = 1022;
var historyitem_type_NvPr = 1023;
var historyitem_type_Ph = 1024;
var historyitem_type_UniNvPr = 1025;
var historyitem_type_StyleRef = 1026;
var historyitem_type_FontRef = 1027;
var historyitem_type_Chart = 1028;
var historyitem_type_ChartSpace = 1029;
var historyitem_type_Legend = 1030;
var historyitem_type_Layout = 1031;
var historyitem_type_LegendEntry = 1032;
var historyitem_type_PivotFmt = 1033;
var historyitem_type_DLbl = 1034;
var historyitem_type_Marker = 1035;
var historyitem_type_PlotArea = 1036;
var historyitem_type_Axis = 1037;
var historyitem_type_NumFmt = 1038;
var historyitem_type_Scaling = 1039;
var historyitem_type_DTable = 1040;
var historyitem_type_LineChart = 1041;
var historyitem_type_DLbls = 1042;
var historyitem_type_UpDownBars = 1043;
var historyitem_type_BarChart = 1044;
var historyitem_type_BubbleChart = 1045;
var historyitem_type_DoughnutChart = 1046;
var historyitem_type_OfPieChart = 1047;
var historyitem_type_PieChart = 1048;
var historyitem_type_RadarChart = 1049;
var historyitem_type_ScatterChart = 1050;
var historyitem_type_StockChart = 1051;
var historyitem_type_SurfaceChart = 1052;
var historyitem_type_BandFmt = 1053;
var historyitem_type_AreaChart = 1054;
var historyitem_type_ScatterSer = 1055;
var historyitem_type_DPt = 1056;
var historyitem_type_ErrBars = 1057;
var historyitem_type_MinusPlus = 1058;
var historyitem_type_NumLit = 1059;
var historyitem_type_NumericPoint = 1060;
var historyitem_type_NumRef = 1061;
var historyitem_type_TrendLine = 1062;
var historyitem_type_Tx = 1063;
var historyitem_type_StrRef = 1064;
var historyitem_type_StrCache = 1065;
var historyitem_type_StrPoint = 1066;
var historyitem_type_XVal = 1067;
var historyitem_type_MultiLvlStrRef = 1068;
var historyitem_type_MultiLvlStrCache = 1068;
var historyitem_type_StringLiteral= 1069;
var historyitem_type_YVal = 1070;
var historyitem_type_AreaSeries = 1071;
var historyitem_type_Cat = 1072;
var historyitem_type_PictureOptions = 1073;
var historyitem_type_RadarSeries = 1074;
var historyitem_type_BarSeries = 1074;
var historyitem_type_LineSeries = 1075;
var historyitem_type_PieSeries = 1076;
var historyitem_type_SurfaceSeries = 1077;
var historyitem_type_BubbleSeries = 1078;
var historyitem_type_ExternalData = 1080;
var historyitem_type_PivotSource = 1081;
var historyitem_type_Protection = 1082;
var historyitem_type_ChartWall = 1083;
var historyitem_type_View3d = 1084;
var historyitem_type_ChartText = 1085;
var historyitem_type_ShapeStyle = 1086;
var historyitem_type_Xfrm = 1087;
var historyitem_type_SpPr = 1088;
var historyitem_type_ClrScheme = 1089;
var historyitem_type_ClrMap = 1090;
var historyitem_type_ExtraClrScheme = 1091;
var historyitem_type_FontCollection = 1092;
var historyitem_type_FontScheme = 1093;
var historyitem_type_FormatScheme = 1094;
var historyitem_type_ThemeElements = 1095;
var historyitem_type_HF = 1096;
var historyitem_type_BgPr = 1097;
var historyitem_type_Bg = 1098;
var historyitem_type_PrintSettings = 1099;
var historyitem_type_HeaderFooterChart = 1100;
var historyitem_type_PageMarginsChart  = 1101;
var historyitem_type_PageSetup = 1102;
var historyitem_type_Shape = 1103;
var historyitem_type_DispUnits = 1104;
var historyitem_type_GroupShape = 1105;
var historyitem_type_ImageShape = 1106;
var historyitem_type_Geometry = 1107;
var historyitem_type_Path = 1108;
var historyitem_type_TextBody = 1109;
var historyitem_type_CatAx = 1110;
var historyitem_type_ValAx = 1111;



// Типы изменений в классе CDocument
var historyitem_Document_AddItem     = 1; // Добавляем элемент в документ
var historyitem_Document_RemoveItem  = 2; // Удаляем элемент из документа
var historyitem_Document_Margin      = 3; // Меняем маргины(поля) документа
var historyitem_Document_PageSize    = 4; // Меняем размер страницы у документа
var historyitem_Document_Orientation = 5; // Меняем ориентацию страниц у документа
var historyitem_Document_DefaultTab  = 6; // Меняем таб по умолчанию

// Типы изменений в классе Paragraph
var historyitem_Paragraph_AddItem                   =  1; // Добавляем элемент в параграф
var historyitem_Paragraph_RemoveItem                =  2; // Удаляем элемент из параграфа
var historyitem_Paragraph_Numbering                 =  3; // Добавляем/Убираем/Изменяем нумерацию у параграфа
var historyitem_Paragraph_Align                     =  4; // Изменяем прилегание параграфа
var historyitem_Paragraph_Ind_First                 =  5; // Изменяем отспут первой строки
var historyitem_Paragraph_Ind_Right                 =  6; // Изменяем правый отступ
var historyitem_Paragraph_Ind_Left                  =  7; // Изменяем левый отступ
var historyitem_Paragraph_ContextualSpacing         =  8; // Изменяем свойство contextualSpacing
var historyitem_Paragraph_KeepLines                 =  9; // Изменяем свойство KeepLines
var historyitem_Paragraph_KeepNext                  = 10; // Изменяем свойство KeepNext
var historyitem_Paragraph_PageBreakBefore           = 11; // Изменяем свойство PageBreakBefore
var historyitem_Paragraph_Spacing_Line              = 12; // Изменяем свойство Spacing.Line
var historyitem_Paragraph_Spacing_LineRule          = 13; // Изменяем свойство Spacing.LineRule
var historyitem_Paragraph_Spacing_Before            = 14; // Изменяем свойство Spacing.Before
var historyitem_Paragraph_Spacing_After             = 15; // Изменяем свойство Spacing.After
var historyitem_Paragraph_Spacing_AfterAutoSpacing  = 16; // Изменяем свойство Spacing.AfterAutoSpacing
var historyitem_Paragraph_Spacing_BeforeAutoSpacing = 17; // Изменяем свойство Spacing.BeforeAutoSpacing
var historyitem_Paragraph_Shd_Value                 = 18; // Изменяем свойство Shd.Value
var historyitem_Paragraph_Shd_Color                 = 19; // Изменяем свойство Shd.Color
var historyitem_Paragraph_WidowControl              = 20; // Изменяем свойство WidowControl
var historyitem_Paragraph_Tabs                      = 21; // Изменяем табы у параграфа
var historyitem_Paragraph_PStyle                    = 22; // Изменяем стиль параграфа
var historyitem_Paragraph_DocNext                   = 23; // Изменяем указатель на следующий объект
var historyitem_Paragraph_DocPrev                   = 24; // Изменяем указатель на предыдущий объект
var historyitem_Paragraph_Parent                    = 25; // Изменяем указатель на родительский объект
var historyitem_Paragraph_Borders_Between           = 26; // Изменяем промежуточную границу
var historyitem_Paragraph_Borders_Bottom            = 27; // Изменяем верхнюю границу
var historyitem_Paragraph_Borders_Left              = 28; // Изменяем левую границу
var historyitem_Paragraph_Borders_Right             = 29; // Изменяем правую границу
var historyitem_Paragraph_Borders_Top               = 30; // Изменяем нижнюю границу
var historyitem_Paragraph_Pr                        = 31; // Изменяем свойства полностью
var historyitem_Paragraph_PresentationPr_Bullet     = 32; // Изменяем свойства нумерации у параграфа в презентации
var historyitem_Paragraph_PresentationPr_Level      = 33; // Изменяем уровень параграфа в презентациях
var historyitem_Paragraph_FramePr                   = 34; // Изменяем настройки рамки
var historyitem_Paragraph_Shd                       = 35; // Изменяем настройки заливки целиком

// Типы изменений в классе ParaRun
var historyitem_ParaRun_AddItem         =  1;
var historyitem_ParaRun_RemoveItem      =  2;
var historyitem_ParaRun_Bold            =  3;
var historyitem_ParaRun_Italic          =  4;
var historyitem_ParaRun_Strikeout       =  5; // �������� ������������ ������
var historyitem_ParaRun_Underline       =  6; // �������� ������������� ������
var historyitem_ParaRun_FontFamily      =  7; // �������� ��� ������
var historyitem_ParaRun_FontSize        =  8; // �������� ������ ������
var historyitem_ParaRun_Color           =  9; // �������� ���� ������
var historyitem_ParaRun_VertAlign       = 10; // �������� ������������ ����������
var historyitem_ParaRun_HighLight       = 11; // �������� ��������� ������
var historyitem_ParaRun_RStyle          = 12; // �������� ����� ������
var historyitem_ParaRun_Spacing         = 13; // �������� ���������� ����� ���������
var historyitem_ParaRun_DStrikeout      = 14; // �������� ������� ������������
var historyitem_ParaRun_Caps            = 15; // �������� ��� ����� �� ���������
var historyitem_ParaRun_SmallCaps       = 16; // �������� ��� ����� �� ����� ���������
var historyitem_ParaRun_Position        = 17; // �������� ������������ ���������
var historyitem_ParaRun_Value           = 18; // �������� ������� ��� ���������
var historyitem_ParaRun_RFonts          = 19; // �������� ��������� �������
var historyitem_ParaRun_Lang            = 20; // �������� ��������� �����
var historyitem_ParaRun_RFonts_Ascii    = 21; // �������� ��������� �������
var historyitem_ParaRun_RFonts_HAnsi    = 22; // �������� ��������� �������
var historyitem_ParaRun_RFonts_CS       = 23; // �������� ��������� �������
var historyitem_ParaRun_RFonts_EastAsia = 24; // �������� ��������� �������
var historyitem_ParaRun_RFonts_Hint     = 25; // �������� ��������� �������
var historyitem_ParaRun_Lang_Bidi       = 26; // �������� ��������� �����
var historyitem_ParaRun_Lang_EastAsia   = 27; // �������� ��������� �����
var historyitem_ParaRun_Lang_Val        = 28; // �������� ��������� �����
var historyitem_ParaRun_TextPr          = 29; // �������� ��� ��������� �������

// Типы изменений в классе ParaTextPr
var historyitem_TextPr_Change     =  1; // Изменяем настройку
var historyitem_TextPr_Bold       =  2; // Изменяем жирность
var historyitem_TextPr_Italic     =  3; // Изменяем наклонность
var historyitem_TextPr_Strikeout  =  4; // Изменяем зачеркивание текста
var historyitem_TextPr_Underline  =  5; // Изменяем подчеркивание текста
var historyitem_TextPr_FontFamily =  6; // Изменяем имя шрифта
var historyitem_TextPr_FontSize   =  7; // Изменяем размер шрифта
var historyitem_TextPr_Color      =  8; // Изменяем цвет текста
var historyitem_TextPr_VertAlign  =  9; // Изменяем вертикальное прилегание
var historyitem_TextPr_HighLight  = 10; // Изменяем выделение текста
var historyitem_TextPr_RStyle     = 11; // Изменяем стиль текста
var historyitem_TextPr_Spacing    = 12; // Изменяем расстояние между символами
var historyitem_TextPr_DStrikeout = 13; // Изменяем двойное зачеркивание
var historyitem_TextPr_Caps       = 14; // Изменяем все буквы на прописные
var historyitem_TextPr_SmallCaps  = 15; // Изменяем все буквы на малые прописные
var historyitem_TextPr_Position   = 16; // Изменяем вертикальное положение
var historyitem_TextPr_Value      = 17; // Изменяем целиком все настройки
var historyitem_TextPr_RFonts     = 18; // Изменяем настройки шрифтов
var historyitem_TextPr_Lang       = 19; // Изменяем настройку языка
var historyitem_TextPr_RFonts_Ascii    = 20; // Изменяем настройки шрифтов
var historyitem_TextPr_RFonts_HAnsi    = 21; // Изменяем настройки шрифтов
var historyitem_TextPr_RFonts_CS       = 22; // Изменяем настройки шрифтов
var historyitem_TextPr_RFonts_EastAsia = 23; // Изменяем настройки шрифтов
var historyitem_TextPr_RFonts_Hint     = 24; // Изменяем настройки шрифтов
var historyitem_TextPr_Lang_Bidi       = 25; // Изменяем настройку языка
var historyitem_TextPr_Lang_EastAsia   = 26; // Изменяем настройку языка
var historyitem_TextPr_Lang_Val        = 27; // Изменяем настройку языка

// Типы изменений в классе ParaDrawing
var historyitem_Drawing_Size              = 1; // Изменяем размер картинки
var historyitem_Drawing_Url               = 2; // Изменяем адрес картинку (т.е. меняем само изображение)
var historyitem_Drawing_DrawingType       = 3; // Изменяем тип объекта (anchor/inline)
var historyitem_Drawing_WrappingType      = 4; // Изменяем тип обтекания
var historyitem_Drawing_Distance          = 5; // Изменяем расстояние до окружающего текста
var historyitem_Drawing_AllowOverlap      = 6; // Изменяем возможность перекрытия плавающих картинок
var historyitem_Drawing_PositionH         = 7; // Изменяем привязку по горизонтали
var historyitem_Drawing_PositionV         = 8; // Изменяем привязку по вертикали
var historyitem_Drawing_AbsoluteTransform = 9;
var historyitem_Drawing_BehindDoc         = 10; // Изменяем положение объекта (за/перед текстом)
var historyitem_Drawing_SetZIndex         = 11;
var historyitem_Drawing_SetGraphicObject  = 12;
var historyitem_CalculateAfterPaste       = 13;
var historyitem_SetSimplePos              = 14;
var historyitem_SetExtent                 = 15;
var historyitem_SetWrapPolygon            = 16;





// Типы изменений в классе CDrawingObjects
var historyitem_DrawingObjects_AddItem    = 1;
var historyitem_DrawingObjects_RemoveItem = 2;

// Типы изменений в классе FlowObjects
var historyitem_FlowObjects_AddItem    = 1;
var historyitem_FlowObjects_RemoveItem = 2;

// Типы изменений в классе FlowImage
var historyitem_FlowImage_Position = 1; // Изменяем позицию картинки
var historyitem_FlowImage_Size     = 2; // Изменяем размер картинки
var historyitem_FlowImage_Paddings = 3; // Изменяем отступы от картинки
var historyitem_FlowImage_PageNum  = 4; // Изменяем номер страницы картинки
var historyitem_FlowImage_Url      = 5; // Изменяем адрес картинку (т.е. меняем само изображение)
var historyitem_FlowImage_Parent   = 6; // Изменяем указатель на родительский объект

// Типы изменений в классе CTable
var historyitem_Table_DocNext               =  1; // Изменяем указатель на следующий объект
var historyitem_Table_DocPrev               =  2; // Изменяем указатель на предыдущий объект
var historyitem_Table_Parent                =  3; // Изменяем указатель на родительский объект
var historyitem_Table_TableW                =  4; // Изменяем ширину таблицы
var historyitem_Table_TableCellMar          =  5; // Изменяем отступы(по умолчанию) внутри ячеек
var historyitem_Table_TableAlign            =  6; // Изменяем прилегание(для inline таблиц)
var historyitem_Table_TableInd              =  7; // Изменяем отступ(для inline таблиц)
var historyitem_Table_TableBorder_Left      =  8; // Изменяем левую границу таблицы
var historyitem_Table_TableBorder_Top       =  9; // Изменяем верхнюю границу таблицы
var historyitem_Table_TableBorder_Right     = 10; // Изменяем правую границу таблицы
var historyitem_Table_TableBorder_Bottom    = 11; // Изменяем нижнюю границу таблицы
var historyitem_Table_TableBorder_InsideH   = 12; // Изменяем внутренюю горизонтальную границу
var historyitem_Table_TableBorder_InsideV   = 13; // Изменяем внутренюю вертикальную границу
var historyitem_Table_TableShd              = 14; // Изменяем заливку таблицы
var historyitem_Table_Inline                = 15; // Изменяем свойствой inline
var historyitem_Table_AddRow                = 16; // Добавляем строку в таблицу
var historyitem_Table_RemoveRow             = 17; // Удаляем строку из таблицы
var historyitem_Table_TableGrid             = 18; // Изменяем сетку колонок
var historyitem_Table_TableLook             = 19; // Изменяем тип условного форматирования таблицы
var historyitem_Table_TableStyleRowBandSize = 20; // Изменяем количество строк в группе
var historyitem_Table_TableStyleColBandSize = 21; // Изменяем количество колонок в группе
var historyitem_Table_TableStyle            = 22; // Изменяем стиль таблицы
var historyitem_Table_AllowOverlap          = 23; // Изменяем возможность перекрытия плавающих таблиц
var historyitem_Table_PositionH             = 24; // Изменяем привязку по горизонтали
var historyitem_Table_PositionV             = 25; // Изменяем привязку по вертикали
var historyitem_Table_Distance              = 26; // Изменяем расстояние до окружающего текста
var historyitem_Table_Pr                    = 27; // Изменяем настройки таблицы целиком
var historyitem_Table_TableLayout           = 28; // Изменяем настройки рассчета ширины колонок

// Типы изменений в классе CTableRow
var historyitem_TableRow_Before      = 1; // Изменяем свойство Before
var historyitem_TableRow_After       = 2; // Изменяем свойство After
var historyitem_TableRow_CellSpacing = 3; // Изменяем свойство CellSpacing
var historyitem_TableRow_Height      = 4; // Изменяем свойство Height
var historyitem_TableRow_AddCell     = 5; // Добавляем ячейку
var historyitem_TableRow_RemoveCell  = 6; // Удаляем ячейку
var historyitem_TableRow_TableHeader = 7; // Изменяем свойство TableHeader
var historyitem_TableRow_Pr          = 8; // Изменяем настройки строки целиком

// Типы изменений в классе CTableCell
var historyitem_TableCell_GridSpan      =  1; // Изменяем горизонтальное объединение
var historyitem_TableCell_Margins       =  2; // Изменяем отступы
var historyitem_TableCell_Shd           =  3; // Изменяем заливку
var historyitem_TableCell_VMerge        =  4; // Изменяем вертикальное объединение
var historyitem_TableCell_Border_Left   =  5; // Изменяем левую границу ячейки
var historyitem_TableCell_Border_Right  =  6; // Изменяем правую границу ячейки
var historyitem_TableCell_Border_Top    =  7; // Изменяем верхнюю границу ячейки
var historyitem_TableCell_Border_Bottom =  8; // Изменяем нижнюю границу ячейки
var historyitem_TableCell_VAlign        =  9; // Изменяем вертикальное выравнивание ячейки
var historyitem_TableCell_W             = 10; // Изменяем ширину ячейки
var historyitem_TableCell_Pr            = 11; // Изменяем настройки целиком

// Типы изменений в классе CDocumentContent
var historyitem_DocumentContent_AddItem     = 1; // Добавляем элемент в документ
var historyitem_DocumentContent_RemoveItem  = 2; // Удаляем элемент из документа

// Типы изменений в классе CFlowTable
var historyitem_FlowTable_Position = 1; // Изменяем позиции
var historyitem_FlowTable_Paddings = 2; // Изменяем отступов
var historyitem_FlowTable_PageNum  = 3; // Изменяем номер страницы у таблицы
var historyitem_FlowTable_Parent   = 4; // Изменяем указатель на родительский объект

// Типы изменений в классе CHeaderFooterController
var historyitem_HdrFtrController_AddItem    = 1; // Добавляем колонтитул
var historyitem_HdrFtrController_RemoveItem = 2; // Удаляем колонтитул

// Типы изменений в классе CHeaderFooter
var historyitem_HdrFtr_BoundY2 = 1; // Изменяем отступ колонтитула (для верхнего от верха,  для нижнего от низа)

// Типы изменений в классе CAbstractNum
var historyitem_AbstractNum_LvlChange    = 1; // Изменили заданный уровень
var historyitem_AbstractNum_TextPrChange = 2; // Изменили текстовую настройку у заданного уровня

// Типы изменений в классе CTableId
var historyitem_TableId_Add   = 1; // Добавили новую ссылку в глобальную таблицу
var historyitem_TableId_Reset = 2; // Изменили Id ссылки

// Типы изменений в классе CComments
var historyitem_Comments_Add    = 1; // Добавили новый комментарий
var historyitem_Comments_Remove = 2; // Удалили комментарий

// Типы изменений в классе СComment
var historyitem_Comment_Change   = 3; // Изменили комментарий
var historyitem_Comment_TypeInfo = 4; // Изменили информацию о типе комментария

// Типы изменений в классе CParaHyperlinkStart
var historyitem_Hyperlink_Value      = 1; // Изменяем значение гиперссылки
var historyitem_Hyperlink_ToolTip    = 2; // Изменяем подсказку гиперссылки
var historyitem_Hyperlink_AddItem    = 3;
var historyitem_Hyperlink_RemoveItem = 4;

//Типы изменений в классе CGraphicObjects
var historyitem_AddNewGraphicObject = 0;
var historyitem_RemoveGraphicObject = 1;


//Типы изменений в классе CGeometry
var historyitem_SetGuideValue = 0;
var historyitem_SetAdjustmentValue = 1;


//Типы изменений в классе WordShape
var historyitem_SetAbsoluteTransform = 0;
var historyitem_SetXfrmShape = 1;
var historyitem_SetRotate = 2;
var historyitem_SetSizes = 3;
var historyitem_SetSizesInGroup = 4;
var historyitem_SetAdjValue = 5;
var historyitem_SetMainGroup = 7;
var historyitem_SetGroup = 8;
var historyitem_InitShape = 9;
var historyitem_AddGraphicObject = 10;
var historyitem_AddToSpTree = 11;
var historyitem_ChangeDiagram = 12;
var historyitem_Init2Shape = 13;
var historyitem_ChangeFill = 14;
var historyitem_ChangeLine = 15;
var historyitem_ChangePresetGeom = 16;
var historyitem_CreatePolyine = 17;
var historyitem_AddDocContent = 18;
var historyitem_SetSizes2 = 19;
var historyitem_RemoveFromSpTree = 20;
var historyitem_RemoveFromArrGraphicObj = 21;
var historyitem_RemoveFromArrGraphicObj2 = 22;
var historyitem_MoveShapeInArray = 23;
var historyitem_UpadteSpTreeBefore = 24;
var historyitem_UpadteSpTreeAfter = 25;
var historyitem_ChangeDiagram2 = 26;
var historyitem_SwapGrObject = 27;
var historyitem_SetSpPr = 28;
var historyitem_SetStyle = 29;
var historyitem_SetBodyPr = 30;
var historyitem_SetTextBoxContent = 31;
var historyitem_SetRasterImage2 = 32;
var historyitem_CalculateAfterCopyInGroup = 33;
var historyitem_SetVerticalShapeAlign = 34;
var historyitem_SetParent = 35;
var historyitem_SetBlipFill = 36;
var historyitem_AutoShapes_AddXAxis = 37;
var historyitem_AutoShapes_AddYAxis = 38;
var historyitem_AutoShapes_AddTitle = 39;
var historyitem_AutoShapes_AddChart = 40;
var historyitem_SetShapeBodyPr = 41;
var historyitem_AutoShapes_SetChartTitleOverlay = 42;
var historyitem_SetCahrtLayout = 43;
var historyitem_AutoShapes_SetChartGroup = 44;
var historyitem_AutoShapes_SetChartTitleType = 45;
var historyitem_SetSetSpPr = 46;
var historyitem_AutoShapes_SetChartTitleTxBody = 47;
var historyitem_AutoShapes_RecalculateAfterResize = 48;
var historyitem_AutoShapes_SetTextPaddings = 49;
var historyitem_AutoShapes_RecalculateChartUndo = 50;
var historyitem_AutoShapes_RecalculateChartRedo = 51;
var historyitem_AutoShapes_UpdateParentWidthHeight = 52;




//Типы изменений в классе GraphicObjects
var historyitem_AddHdrFtrGrObjects = 0;
var historyitem_ChangeColorScheme = 1;

//Типы изменений в классе HeaderFooterGraphicObjects
var historyitem_AddHdr = 0;
var historyitem_AddFtr = 1;
var historyitem_RemoveHdr = 2;
var historyitem_RemoveFtr = 3;



//Типы изменений в классе WordGroupShapes
var historyitem_InternalChanges = 6;
var historyitem_GroupRecalculate = 32;



//Типы изменений в классе WrapPolygon
var historyitem_AddNewPoint = 0;
var historyitem_RemovePoint = 1;
var historyitem_MovePoint   = 2;
var historyitem_UpdateWrapSizes = 3;
var historyitem_ChangePolygon = 4;

// Типы изменений в классе CStyle
var historyitem_Style_TextPr          = 1;  // Изменяем TextPr
var historyitem_Style_ParaPr          = 2;  // Изменяем ParaPr
var historyitem_Style_TablePr         = 3;  // Изменяем TablePr
var historyitem_Style_TableRowPr      = 4;  // Изменяем TableRowPr
var historyitem_Style_TableCellPr     = 5;  // Изменяем TableCellPr
var historyitem_Style_TableBand1Horz  = 6;  // Изменяем TableBand1Horz
var historyitem_Style_TableBand1Vert  = 7;  // Изменяем TableBand1Vert
var historyitem_Style_TableBand2Horz  = 8;  // Изменяем TableBand2Horz
var historyitem_Style_TableBand2Vert  = 9;  // Изменяем TableBand2Vert
var historyitem_Style_TableFirstCol   = 10; // Изменяем TableFirstCol
var historyitem_Style_TableFirstRow   = 11; // Изменяем TableFirstRow
var historyitem_Style_TableLastCol    = 12; // Изменяем TableLastCol
var historyitem_Style_TableLastRow    = 13; // Изменяем TableLastRow
var historyitem_Style_TableTLCell     = 14; // Изменяем TableTLCell
var historyitem_Style_TableTRCell     = 15; // Изменяем TableTRCell
var historyitem_Style_TableBLCell     = 16; // Изменяем TableBLCell
var historyitem_Style_TableBRCell     = 17; // Изменяем TableBRCell
var historyitem_Style_TableWholeTable = 18; // Изменяем TableWholeTable
var historyitem_Style_Name            = 101; // Изменяем Name
var historyitem_Style_BasedOn         = 102; // Изменяем BasedOn
var historyitem_Style_Next            = 103; // Изменяем Next
var historyitem_Style_Type            = 104; // Изменяем Type
var historyitem_Style_QFormat         = 105; // Изменяем QFormat
var historyitem_Style_UiPriority      = 106; // Изменяем UiPriority
var historyitem_Style_Hidden          = 107; // Изменяем Hidden
var historyitem_Style_SemiHidden      = 108; // Изменяем SemiHidden
var historyitem_Style_UnhideWhenUsed  = 109; // Изменяем UnhideWhenUsed

// Типы изменений в классе CStyles
var historyitem_Styles_Add    = 1; // Добавляем стиль
var historyitem_Styles_Remove = 2; // Удаляем стиль

// Тип класса, к которому относится данный элемент истории
var historyitem_State_Unknown         = 0;
var historyitem_State_Document        = 1;
var historyitem_State_DocumentContent = 2;
var historyitem_State_Paragraph       = 3;
var historyitem_State_Table           = 4;

// Типы произошедших изменений
var historyrecalctype_Inline = 0; // Изменения произошли в обычном тексте (с верхним классом CDocument)
var historyrecalctype_Flow   = 1; // Изменения произошли в "плавающем" объекте
var historyrecalctype_HdrFtr = 2; // Изменения произошли в колонтитуле

// Типы классов, в которых происходили изменения (типы нужны для совместного редактирования)
var historyitem_type_Unknown          =  0;
var historyitem_type_TableId          =  1;
var historyitem_type_Document         =  2;
var historyitem_type_Paragraph        =  3;
var historyitem_type_TextPr           =  4;
var historyitem_type_Drawing          =  5;
var historyitem_type_DrawingObjects   =  6;
var historyitem_type_FlowObjects      =  7;
var historyitem_type_FlowImage        =  8;
var historyitem_type_Table            =  9;
var historyitem_type_TableRow         = 10;
var historyitem_type_TableCell        = 11;
var historyitem_type_DocumentContent  = 12;
var historyitem_type_FlowTable        = 13;
var historyitem_type_HdrFtrController = 14;
var historyitem_type_HdrFtr           = 15;
var historyitem_type_AbstractNum      = 16;
var historyitem_type_Comment          = 17;
var historyitem_type_Comments         = 18;
var historyitem_type_Shape            = 19;
var historyitem_type_Image            = 20;
var historyitem_type_GroupShapes      = 21;
var historyitem_type_Geometry         = 22;
var historyitem_type_WrapPolygon      = 23;
var historyitem_type_Chart			  = 24;
var historyitem_type_HdrFtrGrObjects  = 25;
var historyitem_type_GrObjects        = 26;
var historyitem_type_Hyperlink        = 27;
var historyitem_type_ChartGroup       = 28;
var historyitem_type_Style            = 29;
var historyitem_type_Styles           = 30;
var historyitem_type_TextBody         = 31;
var historyitem_type_ChartTitle       = 32;
var historyitem_type_Math			  = 33;
var historyitem_type_CommentMark      = 34;
var historyitem_type_ParaRun          = 35;

//Типы изменений в классе CChartAsGroup
var historyitem_SetCahrtLayout = 1000;

//Типы изменений в классе TexBody
var historyitem_SetShape = 0;
var historyitem_SetDocContent = 1;
var historyitem_SetLstStyle = 2;






