/*
 * (c) Copyright Ascensio System SIA 2010-2017
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation. In accordance with
 * Section 7(a) of the GNU AGPL its Section 15 shall be amended to the effect
 * that Ascensio System SIA expressly excludes the warranty of non-infringement
 * of any third-party rights.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For
 * details, see the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA at Lubanas st. 125a-25, Riga, Latvia,
 * EU, LV-1021.
 *
 * The  interactive user interfaces in modified source and object code versions
 * of the Program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU AGPL version 3.
 *
 * Pursuant to Section 7(b) of the License you must retain the original Product
 * logo when distributing the program. Pursuant to Section 7(e) we decline to
 * grant you any rights under trademark law for use of our trademarks.
 *
 * All the Product's GUI elements, including illustrations and icon sets, as
 * well as technical writing content are licensed under the terms of the
 * Creative Commons Attribution-ShareAlike 4.0 International. See the License
 * terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 */

#include <iostream>
#include <vector>
#include <map>

#include "../../../../../ServerComponents/DesktopEditor/common/File.h"

using namespace std;

void GetConfigMap(std::vector<std::wstring>& _vec1, std::vector<std::wstring>& _vec2)
{
    _vec1.push_back(L"FT_Common.AFM_MAX_ARGUMENTS"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.AFM_STREAM_STATUS_EOC"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.AFM_STREAM_STATUS_EOF"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.AFM_STREAM_STATUS_EOL"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.AFM_STREAM_STATUS_NORMAL"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ASCENDER"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_AXISLABEL"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_AXISTYPE"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_BLENDAXISTYPES"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_BLENDDESIGNMAP"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_BLENDDESIGNPOSITIONS"); _vec2.push_back(L"6");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_B"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_CAPHEIGHT"); _vec2.push_back(L"10");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_CC"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_CHARACTERSET"); _vec2.push_back(L"12");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_CHARACTERS"); _vec2.push_back(L"13");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_CHARWIDTH"); _vec2.push_back(L"11");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_CH"); _vec2.push_back(L"9");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_C"); _vec2.push_back(L"7");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_DESCENDER"); _vec2.push_back(L"14");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ENCODINGSCHEME"); _vec2.push_back(L"15");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ENDAXIS"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ENDCHARMETRICS"); _vec2.push_back(L"17");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ENDCOMPOSITES"); _vec2.push_back(L"18");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ENDDIRECTION"); _vec2.push_back(L"19");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ENDFONTMETRICS"); _vec2.push_back(L"20");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ENDKERNDATA"); _vec2.push_back(L"21");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ENDKERNPAIRS"); _vec2.push_back(L"22");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ENDTRACKKERN"); _vec2.push_back(L"23");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ESCCHAR"); _vec2.push_back(L"24");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_FAMILYNAME"); _vec2.push_back(L"25");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_FONTBBOX"); _vec2.push_back(L"26");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_FONTNAME"); _vec2.push_back(L"27");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_FULLNAME"); _vec2.push_back(L"28");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ISBASEFONT"); _vec2.push_back(L"29");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ISCIDFONT"); _vec2.push_back(L"30");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ISFIXEDPITCH"); _vec2.push_back(L"31");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ISFIXEDV"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_ITALICANGLE"); _vec2.push_back(L"33");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_KPH"); _vec2.push_back(L"35");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_KPX"); _vec2.push_back(L"36");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_KPY"); _vec2.push_back(L"37");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_KP"); _vec2.push_back(L"34");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_L"); _vec2.push_back(L"38");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_MAPPINGSCHEME"); _vec2.push_back(L"39");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_METRICSSETS"); _vec2.push_back(L"40");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_NOTICE"); _vec2.push_back(L"42");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_N"); _vec2.push_back(L"41");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_PCC"); _vec2.push_back(L"43");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_STARTAXIS"); _vec2.push_back(L"44");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_STARTCHARMETRICS"); _vec2.push_back(L"45");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_STARTCOMPOSITES"); _vec2.push_back(L"46");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_STARTDIRECTION"); _vec2.push_back(L"47");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_STARTFONTMETRICS"); _vec2.push_back(L"48");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_STARTKERNDATA"); _vec2.push_back(L"49");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_STARTKERNPAIRS0"); _vec2.push_back(L"51");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_STARTKERNPAIRS1"); _vec2.push_back(L"52");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_STARTKERNPAIRS"); _vec2.push_back(L"50");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_STARTTRACKKERN"); _vec2.push_back(L"53");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_STDHW"); _vec2.push_back(L"54");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_STDVW"); _vec2.push_back(L"55");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_TRACKKERN"); _vec2.push_back(L"56");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_UNDERLINEPOSITION"); _vec2.push_back(L"57");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_UNDERLINETHICKNESS"); _vec2.push_back(L"58");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_UNKNOWN"); _vec2.push_back(L"75");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_VERSION"); _vec2.push_back(L"61");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_VVECTOR"); _vec2.push_back(L"60");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_VV"); _vec2.push_back(L"59");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_W0X"); _vec2.push_back(L"64");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_W0Y"); _vec2.push_back(L"65");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_W0"); _vec2.push_back(L"63");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_W1X"); _vec2.push_back(L"67");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_W1Y"); _vec2.push_back(L"68");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_W1"); _vec2.push_back(L"66");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_WEIGHTVECTOR"); _vec2.push_back(L"72");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_WEIGHT"); _vec2.push_back(L"71");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_WX"); _vec2.push_back(L"69");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_WY"); _vec2.push_back(L"70");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_W"); _vec2.push_back(L"62");
    _vec1.push_back(L"FT_Common.AFM_TOKEN_XHEIGHT"); _vec2.push_back(L"73");
    _vec1.push_back(L"FT_Common.AFM_VALUE_TYPE_BOOL"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.AFM_VALUE_TYPE_FIXED"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.AFM_VALUE_TYPE_INDEX"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.AFM_VALUE_TYPE_INTEGER"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.AFM_VALUE_TYPE_NAME"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.AFM_VALUE_TYPE_STRING"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.ARGS_ARE_WORDS"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.ARGS_ARE_XY_VALUES"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.BDF_PROPERTY_TYPE_ATOM"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.BDF_PROPERTY_TYPE_CARDINAL"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.BDF_PROPERTY_TYPE_INTEGER"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.BDF_PROPERTY_TYPE_NONE"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.CFFCODE_PRIVATE"); _vec2.push_back(L"8192");
    _vec1.push_back(L"FT_Common.CFFCODE_TOPDICT"); _vec2.push_back(L"4096");
    _vec1.push_back(L"FT_Common.CFF_CODE_PRIVATE"); _vec2.push_back(L"8192");
    _vec1.push_back(L"FT_Common.CFF_CODE_TOPDICT"); _vec2.push_back(L"4096");
    _vec1.push_back(L"FT_Common.CFF_COUNT_CHECK_WIDTH"); _vec2.push_back(L"128");
    _vec1.push_back(L"FT_Common.CFF_COUNT_CLEAR_STACK"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.CFF_COUNT_EXACT"); _vec2.push_back(L"64");
    _vec1.push_back(L"FT_Common.CFF_MAX_CID_FONTS"); _vec2.push_back(L"256");
    _vec1.push_back(L"FT_Common.CFF_MAX_OPERANDS"); _vec2.push_back(L"48");
    _vec1.push_back(L"FT_Common.CFF_MAX_STACK_DEPTH"); _vec2.push_back(L"96");
    _vec1.push_back(L"FT_Common.CFF_MAX_SUBRS_CALLS"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.CFF_MAX_TRANS_ELEMENTS"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.ErrorLongJump"); _vec2.push_back(L"-100");
    _vec1.push_back(L"FT_Common.FT_ANGLE_PI2"); _vec2.push_back(L"5898240");
    _vec1.push_back(L"FT_Common.FT_ANGLE_PI"); _vec2.push_back(L"11796480");
    _vec1.push_back(L"FT_Common.FT_CMAP_0"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_CMAP_12"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.FT_CMAP_13"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.FT_CMAP_14"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.FT_CMAP_1"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_CMAP_4"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_CURVE_TAG_CONIC"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_CURVE_TAG_CUBIC"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_CURVE_TAG_HAS_SCANMODE"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.FT_CURVE_TAG_ON"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_CURVE_TAG_TOUCH_BOTH"); _vec2.push_back(L"24");
    _vec1.push_back(L"FT_Common.FT_CURVE_TAG_TOUCH_X"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.FT_CURVE_TAG_TOUCH_Y"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.FT_ENCODING_ADOBE_CUSTOM"); _vec2.push_back(L"1094992451");
    _vec1.push_back(L"FT_Common.FT_ENCODING_ADOBE_EXPERT"); _vec2.push_back(L"1094992453");
    _vec1.push_back(L"FT_Common.FT_ENCODING_ADOBE_LATIN_1"); _vec2.push_back(L"1818326065");
    _vec1.push_back(L"FT_Common.FT_ENCODING_ADOBE_STANDARD"); _vec2.push_back(L"1094995778");
    _vec1.push_back(L"FT_Common.FT_ENCODING_APPLE_ROMAN"); _vec2.push_back(L"1634889070");
    _vec1.push_back(L"FT_Common.FT_ENCODING_BIG5"); _vec2.push_back(L"1651074869");
    _vec1.push_back(L"FT_Common.FT_ENCODING_GB2312"); _vec2.push_back(L"1734484000");
    _vec1.push_back(L"FT_Common.FT_ENCODING_JOHAB"); _vec2.push_back(L"1785686113");
    _vec1.push_back(L"FT_Common.FT_ENCODING_MS_BIG5"); _vec2.push_back(L"1651074869");
    _vec1.push_back(L"FT_Common.FT_ENCODING_MS_GB2312"); _vec2.push_back(L"1734484000");
    _vec1.push_back(L"FT_Common.FT_ENCODING_MS_JOHAB"); _vec2.push_back(L"1785686113");
    _vec1.push_back(L"FT_Common.FT_ENCODING_MS_SJIS"); _vec2.push_back(L"1936353651");
    _vec1.push_back(L"FT_Common.FT_ENCODING_MS_SYMBOL"); _vec2.push_back(L"1937337698");
    _vec1.push_back(L"FT_Common.FT_ENCODING_MS_WANSUNG"); _vec2.push_back(L"2002873971");
    _vec1.push_back(L"FT_Common.FT_ENCODING_NONE"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_ENCODING_OLD_LATIN_2"); _vec2.push_back(L"1818326066");
    _vec1.push_back(L"FT_Common.FT_ENCODING_SJIS"); _vec2.push_back(L"1936353651");
    _vec1.push_back(L"FT_Common.FT_ENCODING_UNICODE"); _vec2.push_back(L"1970170211");
    _vec1.push_back(L"FT_Common.FT_ENCODING_WANSUNG"); _vec2.push_back(L"2002873971");
    _vec1.push_back(L"FT_Common.FT_Err_Array_Too_Large"); _vec2.push_back(L"10");
    _vec1.push_back(L"FT_Common.FT_Err_Bad_Argument"); _vec2.push_back(L"132");
    _vec1.push_back(L"FT_Common.FT_Err_Bbx_Too_Big"); _vec2.push_back(L"184");
    _vec1.push_back(L"FT_Common.FT_Err_CMap_Table_Missing"); _vec2.push_back(L"146");
    _vec1.push_back(L"FT_Common.FT_Err_Cannot_Open_Resource"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_Err_Cannot_Open_Stream"); _vec2.push_back(L"81");
    _vec1.push_back(L"FT_Common.FT_Err_Cannot_Render_Glyph"); _vec2.push_back(L"19");
    _vec1.push_back(L"FT_Common.FT_Err_Code_Overflow"); _vec2.push_back(L"131");
    _vec1.push_back(L"FT_Common.FT_Err_Corrupted_Font_Glyphs"); _vec2.push_back(L"186");
    _vec1.push_back(L"FT_Common.FT_Err_Corrupted_Font_Header"); _vec2.push_back(L"185");
    _vec1.push_back(L"FT_Common.FT_Err_Could_Not_Find_Context"); _vec2.push_back(L"153");
    _vec1.push_back(L"FT_Common.FT_Err_Debug_OpCode"); _vec2.push_back(L"135");
    _vec1.push_back(L"FT_Common.FT_Err_Divide_By_Zero"); _vec2.push_back(L"133");
    _vec1.push_back(L"FT_Common.FT_Err_ENDF_In_Exec_Stream"); _vec2.push_back(L"136");
    _vec1.push_back(L"FT_Common.FT_Err_Execution_Too_Long"); _vec2.push_back(L"139");
    _vec1.push_back(L"FT_Common.FT_Err_Hmtx_Table_Missing"); _vec2.push_back(L"147");
    _vec1.push_back(L"FT_Common.FT_Err_Horiz_Header_Missing"); _vec2.push_back(L"143");
    _vec1.push_back(L"FT_Common.FT_Err_Ignore"); _vec2.push_back(L"162");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Argument"); _vec2.push_back(L"6");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Cache_Handle"); _vec2.push_back(L"39");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_CharMap_Format"); _vec2.push_back(L"150");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_CharMap_Handle"); _vec2.push_back(L"38");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Character_Code"); _vec2.push_back(L"17");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_CodeRange"); _vec2.push_back(L"138");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Composite"); _vec2.push_back(L"21");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Driver_Handle"); _vec2.push_back(L"34");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Face_Handle"); _vec2.push_back(L"35");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_File_Format"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Frame_Operation"); _vec2.push_back(L"86");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Frame_Read"); _vec2.push_back(L"88");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Glyph_Format"); _vec2.push_back(L"18");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Glyph_Index"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Handle"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Horiz_Metrics"); _vec2.push_back(L"149");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Library_Handle"); _vec2.push_back(L"33");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Offset"); _vec2.push_back(L"9");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Opcode"); _vec2.push_back(L"128");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Outline"); _vec2.push_back(L"20");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_PPem"); _vec2.push_back(L"151");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Pixel_Size"); _vec2.push_back(L"23");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Post_Table_Format"); _vec2.push_back(L"154");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Post_Table"); _vec2.push_back(L"155");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Reference"); _vec2.push_back(L"134");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Size_Handle"); _vec2.push_back(L"36");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Slot_Handle"); _vec2.push_back(L"37");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Stream_Handle"); _vec2.push_back(L"40");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Stream_Operation"); _vec2.push_back(L"85");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Stream_Read"); _vec2.push_back(L"84");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Stream_Seek"); _vec2.push_back(L"82");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Stream_Skip"); _vec2.push_back(L"83");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Table"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Version"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.FT_Err_Invalid_Vert_Metrics"); _vec2.push_back(L"152");
    _vec1.push_back(L"FT_Common.FT_Err_Locations_Missing"); _vec2.push_back(L"144");
    _vec1.push_back(L"FT_Common.FT_Err_Lower_Module_Version"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.FT_Err_Missing_Bbx_Field"); _vec2.push_back(L"183");
    _vec1.push_back(L"FT_Common.FT_Err_Missing_Chars_Field"); _vec2.push_back(L"180");
    _vec1.push_back(L"FT_Common.FT_Err_Missing_Encoding_Field"); _vec2.push_back(L"182");
    _vec1.push_back(L"FT_Common.FT_Err_Missing_Font_Field"); _vec2.push_back(L"177");
    _vec1.push_back(L"FT_Common.FT_Err_Missing_Fontboundingbox_Field"); _vec2.push_back(L"179");
    _vec1.push_back(L"FT_Common.FT_Err_Missing_Size_Field"); _vec2.push_back(L"178");
    _vec1.push_back(L"FT_Common.FT_Err_Missing_Startchar_Field"); _vec2.push_back(L"181");
    _vec1.push_back(L"FT_Common.FT_Err_Missing_Startfont_Field"); _vec2.push_back(L"176");
    _vec1.push_back(L"FT_Common.FT_Err_Name_Table_Missing"); _vec2.push_back(L"145");
    _vec1.push_back(L"FT_Common.FT_Err_Nested_DEFS"); _vec2.push_back(L"137");
    _vec1.push_back(L"FT_Common.FT_Err_Nested_Frame_Access"); _vec2.push_back(L"87");
    _vec1.push_back(L"FT_Common.FT_Err_No_Unicode_Glyph_Name"); _vec2.push_back(L"163");
    _vec1.push_back(L"FT_Common.FT_Err_Ok"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_Err_Out_Of_Memory"); _vec2.push_back(L"64");
    _vec1.push_back(L"FT_Common.FT_Err_Post_Table_Missing"); _vec2.push_back(L"148");
    _vec1.push_back(L"FT_Common.FT_Err_Raster_Corrupted"); _vec2.push_back(L"97");
    _vec1.push_back(L"FT_Common.FT_Err_Raster_Negative_Height"); _vec2.push_back(L"99");
    _vec1.push_back(L"FT_Common.FT_Err_Raster_Overflow"); _vec2.push_back(L"98");
    _vec1.push_back(L"FT_Common.FT_Err_Raster_Uninitialized"); _vec2.push_back(L"96");
    _vec1.push_back(L"FT_Common.FT_Err_Stack_Overflow"); _vec2.push_back(L"130");
    _vec1.push_back(L"FT_Common.FT_Err_Stack_Underflow"); _vec2.push_back(L"161");
    _vec1.push_back(L"FT_Common.FT_Err_Syntax_Error"); _vec2.push_back(L"160");
    _vec1.push_back(L"FT_Common.FT_Err_Table_Missing"); _vec2.push_back(L"142");
    _vec1.push_back(L"FT_Common.FT_Err_Too_Few_Arguments"); _vec2.push_back(L"129");
    _vec1.push_back(L"FT_Common.FT_Err_Too_Many_Caches"); _vec2.push_back(L"112");
    _vec1.push_back(L"FT_Common.FT_Err_Too_Many_Drivers"); _vec2.push_back(L"48");
    _vec1.push_back(L"FT_Common.FT_Err_Too_Many_Extensions"); _vec2.push_back(L"49");
    _vec1.push_back(L"FT_Common.FT_Err_Too_Many_Function_Defs"); _vec2.push_back(L"140");
    _vec1.push_back(L"FT_Common.FT_Err_Too_Many_Hints"); _vec2.push_back(L"22");
    _vec1.push_back(L"FT_Common.FT_Err_Too_Many_Instruction_Defs"); _vec2.push_back(L"141");
    _vec1.push_back(L"FT_Common.FT_Err_Unimplemented_Feature"); _vec2.push_back(L"7");
    _vec1.push_back(L"FT_Common.FT_Err_Unknown_File_Format"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_Err_Unlisted_Object"); _vec2.push_back(L"65");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_CID_KEYED"); _vec2.push_back(L"4096");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_EXTERNAL_STREAM"); _vec2.push_back(L"1024");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_FAST_GLYPHS"); _vec2.push_back(L"128");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_FIXED_SIZES"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_FIXED_WIDTH"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_GLYPH_NAMES"); _vec2.push_back(L"512");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_HINTER"); _vec2.push_back(L"2048");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_HORIZONTAL"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_KERNING"); _vec2.push_back(L"64");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_MULTIPLE_MASTERS"); _vec2.push_back(L"256");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_SCALABLE"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_SFNT"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_TRICKY"); _vec2.push_back(L"8192");
    _vec1.push_back(L"FT_Common.FT_FACE_FLAG_VERTICAL"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.FT_GLYPH_BBOX_GRIDFIT"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_GLYPH_BBOX_PIXELS"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.FT_GLYPH_BBOX_SUBPIXELS"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_GLYPH_BBOX_TRUNCATE"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_GLYPH_BBOX_UNSCALED"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_GLYPH_FORMAT_BITMAP"); _vec2.push_back(L"1651078259");
    _vec1.push_back(L"FT_Common.FT_GLYPH_FORMAT_COMPOSITE"); _vec2.push_back(L"1668246896");
    _vec1.push_back(L"FT_Common.FT_GLYPH_FORMAT_NONE"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_GLYPH_FORMAT_OUTLINE"); _vec2.push_back(L"1869968492");
    _vec1.push_back(L"FT_Common.FT_GLYPH_FORMAT_PLOTTER"); _vec2.push_back(L"1886154612");
    _vec1.push_back(L"FT_Common.FT_GLYPH_OWN_BITMAP"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_KERNING_DEFAULT"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_KERNING_UNFITTED"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_KERNING_UNSCALED"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_LOAD_ADVANCE_ONLY"); _vec2.push_back(L"256");
    _vec1.push_back(L"FT_Common.FT_LOAD_CROP_BITMAP"); _vec2.push_back(L"64");
    _vec1.push_back(L"FT_Common.FT_LOAD_DEFAULT"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_LOAD_FORCE_AUTOHINT"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.FT_LOAD_IGNORE_GLOBAL_ADVANCE_WIDTH"); _vec2.push_back(L"512");
    _vec1.push_back(L"FT_Common.FT_LOAD_IGNORE_TRANSFORM"); _vec2.push_back(L"2048");
    _vec1.push_back(L"FT_Common.FT_LOAD_LINEAR_DESIGN"); _vec2.push_back(L"8192");
    _vec1.push_back(L"FT_Common.FT_LOAD_MONOCHROME"); _vec2.push_back(L"4096");
    _vec1.push_back(L"FT_Common.FT_LOAD_NO_AUTOHINT"); _vec2.push_back(L"32768");
    _vec1.push_back(L"FT_Common.FT_LOAD_NO_BITMAP"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.FT_LOAD_NO_HINTING"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_LOAD_NO_RECURSE"); _vec2.push_back(L"1024");
    _vec1.push_back(L"FT_Common.FT_LOAD_NO_SCALE"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_LOAD_PEDANTIC"); _vec2.push_back(L"128");
    _vec1.push_back(L"FT_Common.FT_LOAD_RENDER"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.FT_LOAD_SBITS_ONLY"); _vec2.push_back(L"16384");
    _vec1.push_back(L"FT_Common.FT_LOAD_VERTICAL_LAYOUT"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.FT_MAX_CHARMAP_CACHEABLE"); _vec2.push_back(L"15");
    _vec1.push_back(L"FT_Common.FT_MODULE_DRIVER_HAS_HINTER"); _vec2.push_back(L"1024");
    _vec1.push_back(L"FT_Common.FT_MODULE_DRIVER_NO_OUTLINES"); _vec2.push_back(L"512");
    _vec1.push_back(L"FT_Common.FT_MODULE_DRIVER_SCALABLE"); _vec2.push_back(L"256");
    _vec1.push_back(L"FT_Common.FT_MODULE_FONT_DRIVER"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_MODULE_HINTER"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.FT_MODULE_RENDERER"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_MODULE_STYLER"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.FT_Mod_Err"); _vec2.push_back(L"256");
    _vec1.push_back(L"FT_Common.FT_ORIENTATION_FILL_LEFT"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_ORIENTATION_FILL_RIGHT"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_ORIENTATION_NONE"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_ORIENTATION_POSTSCRIPT"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_ORIENTATION_TRUETYPE"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_OUTLINE_EVEN_ODD_FILL"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_OUTLINE_HIGH_PRECISION"); _vec2.push_back(L"256");
    _vec1.push_back(L"FT_Common.FT_OUTLINE_IGNORE_DROPOUTS"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.FT_OUTLINE_INCLUDE_STUBS"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.FT_OUTLINE_NONE"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_OUTLINE_OWNER"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_OUTLINE_REVERSE_FILL"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.FT_OUTLINE_SINGLE_PASS"); _vec2.push_back(L"512");
    _vec1.push_back(L"FT_Common.FT_OUTLINE_SMART_DROPOUTS"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.FT_PARAM_TAG_UNPATENTED_HINTING"); _vec2.push_back(L"1970172001");
    _vec1.push_back(L"FT_Common.FT_PIXEL_MODE_GRAY2"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.FT_PIXEL_MODE_GRAY4"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.FT_PIXEL_MODE_GRAY"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_PIXEL_MODE_LCD_V"); _vec2.push_back(L"6");
    _vec1.push_back(L"FT_Common.FT_PIXEL_MODE_LCD"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.FT_PIXEL_MODE_MAX"); _vec2.push_back(L"7");
    _vec1.push_back(L"FT_Common.FT_PIXEL_MODE_MONO"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_PIXEL_MODE_NONE"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_RASTER_FLAG_AA"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_RASTER_FLAG_CLIP"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.FT_RASTER_FLAG_DEFAULT"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_RASTER_FLAG_DIRECT"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_RENDER_MODE_LCD_V"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.FT_RENDER_MODE_LCD"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.FT_RENDER_MODE_LIGHT"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_RENDER_MODE_MAX"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.FT_RENDER_MODE_MONO"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_RENDER_MODE_NORMAL"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_SIZE_REQUEST_TYPE_BBOX"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_SIZE_REQUEST_TYPE_CELL"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.FT_SIZE_REQUEST_TYPE_MAX"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.FT_SIZE_REQUEST_TYPE_NOMINAL"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.FT_SIZE_REQUEST_TYPE_REAL_DIM"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_SIZE_REQUEST_TYPE_SCALES"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.FT_STYLE_FLAG_BOLD"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_STYLE_FLAG_ITALIC"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_SUBGLYPH_FLAG_2X2"); _vec2.push_back(L"128");
    _vec1.push_back(L"FT_Common.FT_SUBGLYPH_FLAG_ARGS_ARE_WORDS"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.FT_SUBGLYPH_FLAG_ARGS_ARE_XY_VALUES"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.FT_SUBGLYPH_FLAG_ROUND_XY_TO_GRID"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.FT_SUBGLYPH_FLAG_SCALE"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.FT_SUBGLYPH_FLAG_USE_MY_METRICS"); _vec2.push_back(L"512");
    _vec1.push_back(L"FT_Common.FT_SUBGLYPH_FLAG_XY_SCALE"); _vec2.push_back(L"64");
    _vec1.push_back(L"FT_Common.FT_TRIG_MAX_ITERS"); _vec2.push_back(L"23");
    _vec1.push_back(L"FT_Common.FT_TRIG_SAFE_MSB"); _vec2.push_back(L"29");
    _vec1.push_back(L"FT_Common.FT_TRIG_SCALE"); _vec2.push_back(L"3688454934");
    _vec1.push_back(L"FT_Common.GX_TC_RESERVED_TUPLE_FLAGS"); _vec2.push_back(L"28672");
    _vec1.push_back(L"FT_Common.GX_TC_TUPLES_SHARE_POINT_NUMBERS"); _vec2.push_back(L"32768");
    _vec1.push_back(L"FT_Common.GX_TC_TUPLE_COUNT_MASK"); _vec2.push_back(L"4095");
    _vec1.push_back(L"FT_Common.GX_TI_EMBEDDED_TUPLE_COORD"); _vec2.push_back(L"32768");
    _vec1.push_back(L"FT_Common.GX_TI_INTERMEDIATE_TUPLE"); _vec2.push_back(L"16384");
    _vec1.push_back(L"FT_Common.GX_TI_PRIVATE_POINT_NUMBERS"); _vec2.push_back(L"8192");
    _vec1.push_back(L"FT_Common.GX_TI_RESERVED_TUPLE_FLAG"); _vec2.push_back(L"4096");
    _vec1.push_back(L"FT_Common.GX_TI_TUPLE_INDEX_MASK"); _vec2.push_back(L"4095");
    _vec1.push_back(L"FT_Common.MAX_RUNNABLE_OPCODES"); _vec2.push_back(L"1000000");
    _vec1.push_back(L"FT_Common.MORE_COMPONENTS"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.N_AFM_TOKENS"); _vec2.push_back(L"74");
    _vec1.push_back(L"FT_Common.OVERLAP_COMPOUND"); _vec2.push_back(L"1024");
    _vec1.push_back(L"FT_Common.PS_DICT_BLUE_FUZZ"); _vec2.push_back(L"17");
    _vec1.push_back(L"FT_Common.PS_DICT_BLUE_SCALE"); _vec2.push_back(L"24");
    _vec1.push_back(L"FT_Common.PS_DICT_BLUE_SHIFT"); _vec2.push_back(L"25");
    _vec1.push_back(L"FT_Common.PS_DICT_BLUE_VALUE"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.PS_DICT_CHAR_STRING_KEY"); _vec2.push_back(L"7");
    _vec1.push_back(L"FT_Common.PS_DICT_CHAR_STRING"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.PS_DICT_ENCODING_ENTRY"); _vec2.push_back(L"10");
    _vec1.push_back(L"FT_Common.PS_DICT_ENCODING_TYPE"); _vec2.push_back(L"9");
    _vec1.push_back(L"FT_Common.PS_DICT_FAMILY_BLUE"); _vec2.push_back(L"21");
    _vec1.push_back(L"FT_Common.PS_DICT_FAMILY_NAME"); _vec2.push_back(L"39");
    _vec1.push_back(L"FT_Common.PS_DICT_FAMILY_OTHER_BLUE"); _vec2.push_back(L"23");
    _vec1.push_back(L"FT_Common.PS_DICT_FONT_BBOX"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.PS_DICT_FONT_MATRIX"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.PS_DICT_FONT_NAME"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.PS_DICT_FONT_TYPE"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.PS_DICT_FORCE_BOLD"); _vec2.push_back(L"30");
    _vec1.push_back(L"FT_Common.PS_DICT_FS_TYPE"); _vec2.push_back(L"44");
    _vec1.push_back(L"FT_Common.PS_DICT_FULL_NAME"); _vec2.push_back(L"38");
    _vec1.push_back(L"FT_Common.PS_DICT_IS_FIXED_PITCH"); _vec2.push_back(L"41");
    _vec1.push_back(L"FT_Common.PS_DICT_ITALIC_ANGLE"); _vec2.push_back(L"45");
    _vec1.push_back(L"FT_Common.PS_DICT_LANGUAGE_GROUP"); _vec2.push_back(L"35");
    _vec1.push_back(L"FT_Common.PS_DICT_LEN_IV"); _vec2.push_back(L"33");
    _vec1.push_back(L"FT_Common.PS_DICT_MAX"); _vec2.push_back(L"45");
    _vec1.push_back(L"FT_Common.PS_DICT_MIN_FEATURE"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.PS_DICT_NOTICE"); _vec2.push_back(L"37");
    _vec1.push_back(L"FT_Common.PS_DICT_NUM_BLUE_VALUES"); _vec2.push_back(L"15");
    _vec1.push_back(L"FT_Common.PS_DICT_NUM_CHAR_STRINGS"); _vec2.push_back(L"6");
    _vec1.push_back(L"FT_Common.PS_DICT_NUM_FAMILY_BLUES"); _vec2.push_back(L"20");
    _vec1.push_back(L"FT_Common.PS_DICT_NUM_FAMILY_OTHER_BLUES"); _vec2.push_back(L"22");
    _vec1.push_back(L"FT_Common.PS_DICT_NUM_OTHER_BLUES"); _vec2.push_back(L"18");
    _vec1.push_back(L"FT_Common.PS_DICT_NUM_STEM_SNAP_H"); _vec2.push_back(L"26");
    _vec1.push_back(L"FT_Common.PS_DICT_NUM_STEM_SNAP_V"); _vec2.push_back(L"28");
    _vec1.push_back(L"FT_Common.PS_DICT_NUM_SUBRS"); _vec2.push_back(L"11");
    _vec1.push_back(L"FT_Common.PS_DICT_OTHER_BLUE"); _vec2.push_back(L"19");
    _vec1.push_back(L"FT_Common.PS_DICT_PAINT_TYPE"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.PS_DICT_PASSWORD"); _vec2.push_back(L"34");
    _vec1.push_back(L"FT_Common.PS_DICT_RND_STEM_UP"); _vec2.push_back(L"31");
    _vec1.push_back(L"FT_Common.PS_DICT_STD_HW"); _vec2.push_back(L"13");
    _vec1.push_back(L"FT_Common.PS_DICT_STD_VW"); _vec2.push_back(L"14");
    _vec1.push_back(L"FT_Common.PS_DICT_STEM_SNAP_H"); _vec2.push_back(L"27");
    _vec1.push_back(L"FT_Common.PS_DICT_STEM_SNAP_V"); _vec2.push_back(L"29");
    _vec1.push_back(L"FT_Common.PS_DICT_SUBR"); _vec2.push_back(L"12");
    _vec1.push_back(L"FT_Common.PS_DICT_UNDERLINE_POSITION"); _vec2.push_back(L"42");
    _vec1.push_back(L"FT_Common.PS_DICT_UNDERLINE_THICKNESS"); _vec2.push_back(L"43");
    _vec1.push_back(L"FT_Common.PS_DICT_UNIQUE_ID"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.PS_DICT_VERSION"); _vec2.push_back(L"36");
    _vec1.push_back(L"FT_Common.PS_DICT_WEIGHT"); _vec2.push_back(L"40");
    _vec1.push_back(L"FT_Common.ROUND_XY_TO_GRID"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.SCALED_COMPONENT_OFFSET"); _vec2.push_back(L"2048");
    _vec1.push_back(L"FT_Common.SPH_FDEF_DIAGONAL_STROKE"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.SPH_FDEF_INLINE_DELTA_1"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.SPH_FDEF_INLINE_DELTA_2"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.SPH_FDEF_SPACING_1"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.SPH_FDEF_SPACING_2"); _vec2.push_back(L"64");
    _vec1.push_back(L"FT_Common.SPH_FDEF_TTFAUTOHINT_1"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.SPH_FDEF_TYPEMAN_DIAGENDCTRL"); _vec2.push_back(L"256");
    _vec1.push_back(L"FT_Common.SPH_FDEF_TYPEMAN_STROKES"); _vec2.push_back(L"128");
    _vec1.push_back(L"FT_Common.SPH_FDEF_VACUFORM_ROUND_1"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.SPH_OPTION_BITMAP_WIDTHS"); _vec2.push_back(L"false");
    _vec1.push_back(L"FT_Common.SPH_OPTION_SET_COMPATIBLE_WIDTHS"); _vec2.push_back(L"false");
    _vec1.push_back(L"FT_Common.SPH_OPTION_SET_GRAYSCALE"); _vec2.push_back(L"false");
    _vec1.push_back(L"FT_Common.SPH_OPTION_SET_RASTERIZER_VERSION"); _vec2.push_back(L"38");
    _vec1.push_back(L"FT_Common.SPH_OPTION_SET_SUBPIXEL"); _vec2.push_back(L"true");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_ALLOW_X_DMOVE"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_ALWAYS_DO_DELTAP"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_ALWAYS_SKIP_DELTAP"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_COURIER_NEW_2_HACK"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_DEEMBOLDEN"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_DO_SHPIX"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_EMBOLDEN"); _vec2.push_back(L"64");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_MIAP_HACK"); _vec2.push_back(L"128");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_NORMAL_ROUND"); _vec2.push_back(L"256");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_NO_ALIGNRP_AFTER_IUP"); _vec2.push_back(L"512");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_NO_CALL_AFTER_IUP"); _vec2.push_back(L"1024");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_NO_DELTAP_AFTER_IUP"); _vec2.push_back(L"2048");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_PIXEL_HINTING"); _vec2.push_back(L"4096");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_RASTERIZER_35"); _vec2.push_back(L"8192");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_ROUND_NONPIXEL_Y_MOVES"); _vec2.push_back(L"16384");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_SKIP_IUP"); _vec2.push_back(L"32768");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_SKIP_NONPIXEL_Y_MOVES_DELTAP"); _vec2.push_back(L"524288");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_SKIP_NONPIXEL_Y_MOVES"); _vec2.push_back(L"65536");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_SKIP_OFFPIXEL_Y_MOVES"); _vec2.push_back(L"131072");
    _vec1.push_back(L"FT_Common.SPH_TWEAK_TIMES_NEW_ROMAN_HACK"); _vec2.push_back(L"262144");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_0"); _vec2.push_back(L"48");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_7"); _vec2.push_back(L"55");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_9"); _vec2.push_back(L"57");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_A"); _vec2.push_back(L"65");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_BS"); _vec2.push_back(L"47");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_B"); _vec2.push_back(L"66");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_C"); _vec2.push_back(L"67");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_D"); _vec2.push_back(L"68");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_E"); _vec2.push_back(L"69");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_F"); _vec2.push_back(L"70");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_G"); _vec2.push_back(L"71");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_H"); _vec2.push_back(L"72");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_I"); _vec2.push_back(L"73");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_J"); _vec2.push_back(L"74");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_K"); _vec2.push_back(L"75");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_LOGOR"); _vec2.push_back(L"124");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_LS1"); _vec2.push_back(L"40");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_LS2"); _vec2.push_back(L"91");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_LS3"); _vec2.push_back(L"123");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_L"); _vec2.push_back(L"76");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_MATH_1"); _vec2.push_back(L"60");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_MATH_2"); _vec2.push_back(L"62");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_MATH_3"); _vec2.push_back(L"37");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_MATH_MINUS"); _vec2.push_back(L"45");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_MATH_PLUS"); _vec2.push_back(L"43");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_M"); _vec2.push_back(L"77");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_N"); _vec2.push_back(L"78");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_O"); _vec2.push_back(L"79");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_POINT"); _vec2.push_back(L"46");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_P"); _vec2.push_back(L"80");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_Q"); _vec2.push_back(L"81");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_RS1"); _vec2.push_back(L"41");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_RS2"); _vec2.push_back(L"93");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_RS3"); _vec2.push_back(L"125");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_R"); _vec2.push_back(L"82");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_S0"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_SERP"); _vec2.push_back(L"59");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_SF"); _vec2.push_back(L"12");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_SHARP"); _vec2.push_back(L"35");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_SN"); _vec2.push_back(L"10");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_SPACE"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_SR"); _vec2.push_back(L"13");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_SS"); _vec2.push_back(L"92");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_ST"); _vec2.push_back(L"9");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_S"); _vec2.push_back(L"83");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_T"); _vec2.push_back(L"84");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_U"); _vec2.push_back(L"85");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_VOPROS"); _vec2.push_back(L"63");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_VOSCL"); _vec2.push_back(L"33");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_V"); _vec2.push_back(L"86");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_W"); _vec2.push_back(L"87");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_X"); _vec2.push_back(L"88");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_Y"); _vec2.push_back(L"89");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_Z"); _vec2.push_back(L"90");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST__"); _vec2.push_back(L"95");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_a"); _vec2.push_back(L"97");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_b"); _vec2.push_back(L"98");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_c"); _vec2.push_back(L"99");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_d"); _vec2.push_back(L"100");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_e"); _vec2.push_back(L"101");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_f"); _vec2.push_back(L"102");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_g"); _vec2.push_back(L"103");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_h"); _vec2.push_back(L"104");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_i"); _vec2.push_back(L"105");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_j"); _vec2.push_back(L"106");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_k"); _vec2.push_back(L"107");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_l"); _vec2.push_back(L"108");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_m"); _vec2.push_back(L"109");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_n"); _vec2.push_back(L"110");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_o"); _vec2.push_back(L"111");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_p"); _vec2.push_back(L"112");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_q"); _vec2.push_back(L"113");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_r"); _vec2.push_back(L"114");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_s"); _vec2.push_back(L"115");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_t"); _vec2.push_back(L"116");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_u"); _vec2.push_back(L"117");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_v"); _vec2.push_back(L"118");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_w"); _vec2.push_back(L"119");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_x"); _vec2.push_back(L"120");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_y"); _vec2.push_back(L"121");
    _vec1.push_back(L"FT_Common.SYMBOL_CONST_z"); _vec2.push_back(L"122");
    _vec1.push_back(L"FT_Common.T1_BLEND_BLUE_SCALE"); _vec2.push_back(L"9");
    _vec1.push_back(L"FT_Common.T1_BLEND_BLUE_SHIFT"); _vec2.push_back(L"10");
    _vec1.push_back(L"FT_Common.T1_BLEND_BLUE_VALUES"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.T1_BLEND_FAMILY_BLUES"); _vec2.push_back(L"11");
    _vec1.push_back(L"FT_Common.T1_BLEND_FAMILY_OTHER_BLUES"); _vec2.push_back(L"12");
    _vec1.push_back(L"FT_Common.T1_BLEND_FORCE_BOLD"); _vec2.push_back(L"13");
    _vec1.push_back(L"FT_Common.T1_BLEND_ITALIC_ANGLE"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.T1_BLEND_MAX"); _vec2.push_back(L"14");
    _vec1.push_back(L"FT_Common.T1_BLEND_OTHER_BLUES"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.T1_BLEND_STANDARD_HEIGHT"); _vec2.push_back(L"6");
    _vec1.push_back(L"FT_Common.T1_BLEND_STANDARD_WIDTH"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.T1_BLEND_STEM_SNAP_HEIGHTS"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.T1_BLEND_STEM_SNAP_WIDTHS"); _vec2.push_back(L"7");
    _vec1.push_back(L"FT_Common.T1_BLEND_UNDERLINE_POSITION"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.T1_BLEND_UNDERLINE_THICKNESS"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.T1_ENCODING_TYPE_ARRAY"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.T1_ENCODING_TYPE_EXPERT"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.T1_ENCODING_TYPE_ISOLATIN1"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.T1_ENCODING_TYPE_NONE"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.T1_ENCODING_TYPE_STANDARD"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.T1_FIELD_DICT_FONTDICT"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.T1_FIELD_DICT_PRIVATE"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.T1_FIELD_LOCATION_BBOX"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.T1_FIELD_LOCATION_BLEND"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.T1_FIELD_LOCATION_CID_INFO"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.T1_FIELD_LOCATION_FACE"); _vec2.push_back(L"7");
    _vec1.push_back(L"FT_Common.T1_FIELD_LOCATION_FONT_DICT"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.T1_FIELD_LOCATION_FONT_EXTRA"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.T1_FIELD_LOCATION_FONT_INFO"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.T1_FIELD_LOCATION_LOADER"); _vec2.push_back(L"6");
    _vec1.push_back(L"FT_Common.T1_FIELD_LOCATION_MAX"); _vec2.push_back(L"9");
    _vec1.push_back(L"FT_Common.T1_FIELD_LOCATION_PRIVATE"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.T1_FIELD_TYPE_BBOX"); _vec2.push_back(L"7");
    _vec1.push_back(L"FT_Common.T1_FIELD_TYPE_BOOL"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.T1_FIELD_TYPE_CALLBACK"); _vec2.push_back(L"10");
    _vec1.push_back(L"FT_Common.T1_FIELD_TYPE_FIXED_1000"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.T1_FIELD_TYPE_FIXED_ARRAY"); _vec2.push_back(L"9");
    _vec1.push_back(L"FT_Common.T1_FIELD_TYPE_FIXED"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.T1_FIELD_TYPE_INTEGER_ARRAY"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.T1_FIELD_TYPE_INTEGER"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.T1_FIELD_TYPE_KEY"); _vec2.push_back(L"6");
    _vec1.push_back(L"FT_Common.T1_FIELD_TYPE_MAX"); _vec2.push_back(L"11");
    _vec1.push_back(L"FT_Common.T1_FIELD_TYPE_NONE"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.T1_FIELD_TYPE_STRING"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.T1_FONTDIR_AFTER_PRIVATE"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.T1_MAX_CHARSTRINGS_OPERANDS"); _vec2.push_back(L"256");
    _vec1.push_back(L"FT_Common.T1_MAX_MM_AXIS"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.T1_MAX_MM_DESIGNS"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.T1_MAX_MM_MAP_POINTS"); _vec2.push_back(L"20");
    _vec1.push_back(L"FT_Common.T1_MAX_SUBRS_CALLS"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.T1_MAX_TABLE_ELEMENTS"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.T1_PRIVATE"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.T1_Parse_Have_Moveto"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.T1_Parse_Have_Path"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.T1_Parse_Have_Width"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.T1_Parse_Start"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.T1_TOKEN_TYPE_ANY"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.T1_TOKEN_TYPE_ARRAY"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.T1_TOKEN_TYPE_KEY"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.T1_TOKEN_TYPE_MAX"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.T1_TOKEN_TYPE_NONE"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.T1_TOKEN_TYPE_STRING"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.TABLE_EXTEND"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.TTAG_BASE"); _vec2.push_back(L"1111577413");
    _vec1.push_back(L"FT_Common.TTAG_BDF"); _vec2.push_back(L"1111770656");
    _vec1.push_back(L"FT_Common.TTAG_CFF"); _vec2.push_back(L"1128678944");
    _vec1.push_back(L"FT_Common.TTAG_CID"); _vec2.push_back(L"1128875040");
    _vec1.push_back(L"FT_Common.TTAG_DSIG"); _vec2.push_back(L"1146308935");
    _vec1.push_back(L"FT_Common.TTAG_EBDT"); _vec2.push_back(L"1161970772");
    _vec1.push_back(L"FT_Common.TTAG_EBLC"); _vec2.push_back(L"1161972803");
    _vec1.push_back(L"FT_Common.TTAG_EBSC"); _vec2.push_back(L"1161974595");
    _vec1.push_back(L"FT_Common.TTAG_FOND"); _vec2.push_back(L"1179602500");
    _vec1.push_back(L"FT_Common.TTAG_GDEF"); _vec2.push_back(L"1195656518");
    _vec1.push_back(L"FT_Common.TTAG_GPOS"); _vec2.push_back(L"1196445523");
    _vec1.push_back(L"FT_Common.TTAG_GSUB"); _vec2.push_back(L"1196643650");
    _vec1.push_back(L"FT_Common.TTAG_JSTF"); _vec2.push_back(L"1246975046");
    _vec1.push_back(L"FT_Common.TTAG_LTSH"); _vec2.push_back(L"1280594760");
    _vec1.push_back(L"FT_Common.TTAG_LWFN"); _vec2.push_back(L"1280788046");
    _vec1.push_back(L"FT_Common.TTAG_MATH"); _vec2.push_back(L"1296127048");
    _vec1.push_back(L"FT_Common.TTAG_META"); _vec2.push_back(L"1296389185");
    _vec1.push_back(L"FT_Common.TTAG_MMFX"); _vec2.push_back(L"1296909912");
    _vec1.push_back(L"FT_Common.TTAG_MMSD"); _vec2.push_back(L"1296913220");
    _vec1.push_back(L"FT_Common.TTAG_OS2"); _vec2.push_back(L"1330851634");
    _vec1.push_back(L"FT_Common.TTAG_OTTO"); _vec2.push_back(L"1330926671");
    _vec1.push_back(L"FT_Common.TTAG_PCLT"); _vec2.push_back(L"1346587732");
    _vec1.push_back(L"FT_Common.TTAG_POST"); _vec2.push_back(L"1347375956");
    _vec1.push_back(L"FT_Common.TTAG_SING"); _vec2.push_back(L"1397313095");
    _vec1.push_back(L"FT_Common.TTAG_TYP1"); _vec2.push_back(L"1415139377");
    _vec1.push_back(L"FT_Common.TTAG_VDMX"); _vec2.push_back(L"1447316824");
    _vec1.push_back(L"FT_Common.TTAG_avar"); _vec2.push_back(L"1635148146");
    _vec1.push_back(L"FT_Common.TTAG_bdat"); _vec2.push_back(L"1650745716");
    _vec1.push_back(L"FT_Common.TTAG_bhed"); _vec2.push_back(L"1651008868");
    _vec1.push_back(L"FT_Common.TTAG_bloc"); _vec2.push_back(L"1651273571");
    _vec1.push_back(L"FT_Common.TTAG_bsln"); _vec2.push_back(L"1651731566");
    _vec1.push_back(L"FT_Common.TTAG_cmap"); _vec2.push_back(L"1668112752");
    _vec1.push_back(L"FT_Common.TTAG_cvar"); _vec2.push_back(L"1668702578");
    _vec1.push_back(L"FT_Common.TTAG_cvt"); _vec2.push_back(L"1668707360");
    _vec1.push_back(L"FT_Common.TTAG_feat"); _vec2.push_back(L"1717920116");
    _vec1.push_back(L"FT_Common.TTAG_fpgm"); _vec2.push_back(L"1718642541");
    _vec1.push_back(L"FT_Common.TTAG_fvar"); _vec2.push_back(L"1719034226");
    _vec1.push_back(L"FT_Common.TTAG_gasp"); _vec2.push_back(L"1734439792");
    _vec1.push_back(L"FT_Common.TTAG_glyf"); _vec2.push_back(L"1735162214");
    _vec1.push_back(L"FT_Common.TTAG_gvar"); _vec2.push_back(L"1735811442");
    _vec1.push_back(L"FT_Common.TTAG_hdmx"); _vec2.push_back(L"1751412088");
    _vec1.push_back(L"FT_Common.TTAG_head"); _vec2.push_back(L"1751474532");
    _vec1.push_back(L"FT_Common.TTAG_hhea"); _vec2.push_back(L"1751672161");
    _vec1.push_back(L"FT_Common.TTAG_hmtx"); _vec2.push_back(L"1752003704");
    _vec1.push_back(L"FT_Common.TTAG_just"); _vec2.push_back(L"1786082164");
    _vec1.push_back(L"FT_Common.TTAG_kern"); _vec2.push_back(L"1801810542");
    _vec1.push_back(L"FT_Common.TTAG_lcar"); _vec2.push_back(L"1818452338");
    _vec1.push_back(L"FT_Common.TTAG_loca"); _vec2.push_back(L"1819239265");
    _vec1.push_back(L"FT_Common.TTAG_maxp"); _vec2.push_back(L"1835104368");
    _vec1.push_back(L"FT_Common.TTAG_mort"); _vec2.push_back(L"1836020340");
    _vec1.push_back(L"FT_Common.TTAG_morx"); _vec2.push_back(L"1836020344");
    _vec1.push_back(L"FT_Common.TTAG_name"); _vec2.push_back(L"1851878757");
    _vec1.push_back(L"FT_Common.TTAG_opbd"); _vec2.push_back(L"1869636196");
    _vec1.push_back(L"FT_Common.TTAG_opsz"); _vec2.push_back(L"1869640570");
    _vec1.push_back(L"FT_Common.TTAG_post"); _vec2.push_back(L"1886352244");
    _vec1.push_back(L"FT_Common.TTAG_prep"); _vec2.push_back(L"1886545264");
    _vec1.push_back(L"FT_Common.TTAG_prop"); _vec2.push_back(L"1886547824");
    _vec1.push_back(L"FT_Common.TTAG_sfnt"); _vec2.push_back(L"1936092788");
    _vec1.push_back(L"FT_Common.TTAG_slnt"); _vec2.push_back(L"1936486004");
    _vec1.push_back(L"FT_Common.TTAG_trak"); _vec2.push_back(L"1953653099");
    _vec1.push_back(L"FT_Common.TTAG_true"); _vec2.push_back(L"1953658213");
    _vec1.push_back(L"FT_Common.TTAG_ttcf"); _vec2.push_back(L"1953784678");
    _vec1.push_back(L"FT_Common.TTAG_ttc"); _vec2.push_back(L"1953784608");
    _vec1.push_back(L"FT_Common.TTAG_typ1"); _vec2.push_back(L"1954115633");
    _vec1.push_back(L"FT_Common.TTAG_vhea"); _vec2.push_back(L"1986553185");
    _vec1.push_back(L"FT_Common.TTAG_vmtx"); _vec2.push_back(L"1986884728");
    _vec1.push_back(L"FT_Common.TTAG_wdth"); _vec2.push_back(L"2003072104");
    _vec1.push_back(L"FT_Common.TTAG_wght"); _vec2.push_back(L"2003265652");
    _vec1.push_back(L"FT_Common.TT_ADOBE_ID_CUSTOM"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.TT_ADOBE_ID_EXPERT"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.TT_ADOBE_ID_LATIN_1"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.TT_ADOBE_ID_STANDARD"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.TT_APPLE_ID_DEFAULT"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.TT_APPLE_ID_ISO_10646"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.TT_APPLE_ID_UNICODE_1_1"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.TT_APPLE_ID_UNICODE_2_0"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.TT_APPLE_ID_UNICODE_32"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.TT_APPLE_ID_VARIANT_SELECTOR"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.TT_CMAP_FLAG_OVERLAPPING"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.TT_CMAP_FLAG_UNSORTED"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.TT_INTERPRETER_VERSION_35"); _vec2.push_back(L"35");
    _vec1.push_back(L"FT_Common.TT_INTERPRETER_VERSION_38"); _vec2.push_back(L"38");
    _vec1.push_back(L"FT_Common.TT_MAC_ID_ROMAN"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.TT_MAX_CODE_RANGES"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.TT_MS_ID_BIG_5"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.TT_MS_ID_GB2312"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.TT_MS_ID_JOHAB"); _vec2.push_back(L"6");
    _vec1.push_back(L"FT_Common.TT_MS_ID_SJIS"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.TT_MS_ID_SYMBOL_CS"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.TT_MS_ID_UCS_4"); _vec2.push_back(L"10");
    _vec1.push_back(L"FT_Common.TT_MS_ID_UNICODE_CS"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.TT_MS_ID_WANSUNG"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_CID_FINDFONT_NAME"); _vec2.push_back(L"20");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_COPYRIGHT"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_DESCRIPTION"); _vec2.push_back(L"10");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_DESIGNER_URL"); _vec2.push_back(L"12");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_DESIGNER"); _vec2.push_back(L"9");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_FONT_FAMILY"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_FONT_SUBFAMILY"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_FULL_NAME"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_LICENSE_URL"); _vec2.push_back(L"14");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_LICENSE"); _vec2.push_back(L"13");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_MAC_FULL_NAME"); _vec2.push_back(L"18");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_MANUFACTURER"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_PREFERRED_FAMILY"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_PREFERRED_SUBFAMILY"); _vec2.push_back(L"17");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_PS_NAME"); _vec2.push_back(L"6");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_SAMPLE_TEXT"); _vec2.push_back(L"19");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_TRADEMARK"); _vec2.push_back(L"7");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_UNIQUE_ID"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_VENDOR_URL"); _vec2.push_back(L"11");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_VERSION_STRING"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_WWS_FAMILY"); _vec2.push_back(L"21");
    _vec1.push_back(L"FT_Common.TT_NAME_ID_WWS_SUBFAMILY"); _vec2.push_back(L"22");
    _vec1.push_back(L"FT_Common.TT_PLATFORM_ADOBE"); _vec2.push_back(L"7");
    _vec1.push_back(L"FT_Common.TT_PLATFORM_APPLE_UNICODE"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.TT_PLATFORM_CUSTOM"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.TT_PLATFORM_ISO"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.TT_PLATFORM_MACINTOSH"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.TT_PLATFORM_MICROSOFT"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.UNSCALED_COMPONENT_OFFSET"); _vec2.push_back(L"4096");
    _vec1.push_back(L"FT_Common.USE_MY_METRICS"); _vec2.push_back(L"512");
    _vec1.push_back(L"FT_Common.WE_HAVE_AN_XY_SCALE"); _vec2.push_back(L"64");
    _vec1.push_back(L"FT_Common.WE_HAVE_A_2X2"); _vec2.push_back(L"128");
    _vec1.push_back(L"FT_Common.WE_HAVE_A_SCALE"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.WE_HAVE_INSTR"); _vec2.push_back(L"256");
    _vec1.push_back(L"FT_Common.a_c"); _vec2.push_back(L"256");
    _vec1.push_back(L"FT_Common.a_i"); _vec2.push_back(L"4294967296");
    _vec1.push_back(L"FT_Common.a_s"); _vec2.push_back(L"65536");
    _vec1.push_back(L"FT_Common.cff_kind_bool"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.cff_kind_callback"); _vec2.push_back(L"7");
    _vec1.push_back(L"FT_Common.cff_kind_delta"); _vec2.push_back(L"6");
    _vec1.push_back(L"FT_Common.cff_kind_fixed_thousand"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.cff_kind_fixed"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.cff_kind_max"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.cff_kind_none"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.cff_kind_num"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.cff_kind_string"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.cff_op_abs"); _vec2.push_back(L"26");
    _vec1.push_back(L"FT_Common.cff_op_add"); _vec2.push_back(L"27");
    _vec1.push_back(L"FT_Common.cff_op_and"); _vec2.push_back(L"44");
    _vec1.push_back(L"FT_Common.cff_op_blend"); _vec2.push_back(L"34");
    _vec1.push_back(L"FT_Common.cff_op_callgsubr"); _vec2.push_back(L"50");
    _vec1.push_back(L"FT_Common.cff_op_callothersubr"); _vec2.push_back(L"54");
    _vec1.push_back(L"FT_Common.cff_op_callsubr"); _vec2.push_back(L"49");
    _vec1.push_back(L"FT_Common.cff_op_closepath"); _vec2.push_back(L"53");
    _vec1.push_back(L"FT_Common.cff_op_cntrmask"); _vec2.push_back(L"24");
    _vec1.push_back(L"FT_Common.cff_op_div"); _vec2.push_back(L"29");
    _vec1.push_back(L"FT_Common.cff_op_dotsection"); _vec2.push_back(L"25");
    _vec1.push_back(L"FT_Common.cff_op_drop"); _vec2.push_back(L"35");
    _vec1.push_back(L"FT_Common.cff_op_dup"); _vec2.push_back(L"39");
    _vec1.push_back(L"FT_Common.cff_op_endchar"); _vec2.push_back(L"18");
    _vec1.push_back(L"FT_Common.cff_op_eq"); _vec2.push_back(L"47");
    _vec1.push_back(L"FT_Common.cff_op_exch"); _vec2.push_back(L"36");
    _vec1.push_back(L"FT_Common.cff_op_flex1"); _vec2.push_back(L"17");
    _vec1.push_back(L"FT_Common.cff_op_flex"); _vec2.push_back(L"14");
    _vec1.push_back(L"FT_Common.cff_op_get"); _vec2.push_back(L"41");
    _vec1.push_back(L"FT_Common.cff_op_hflex1"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.cff_op_hflex"); _vec2.push_back(L"15");
    _vec1.push_back(L"FT_Common.cff_op_hhcurveto"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.cff_op_hintmask"); _vec2.push_back(L"23");
    _vec1.push_back(L"FT_Common.cff_op_hlineto"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.cff_op_hmoveto"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.cff_op_hsbw"); _vec2.push_back(L"52");
    _vec1.push_back(L"FT_Common.cff_op_hstemhm"); _vec2.push_back(L"21");
    _vec1.push_back(L"FT_Common.cff_op_hstem"); _vec2.push_back(L"19");
    _vec1.push_back(L"FT_Common.cff_op_hvcurveto"); _vec2.push_back(L"9");
    _vec1.push_back(L"FT_Common.cff_op_ifelse"); _vec2.push_back(L"48");
    _vec1.push_back(L"FT_Common.cff_op_index"); _vec2.push_back(L"37");
    _vec1.push_back(L"FT_Common.cff_op_load"); _vec2.push_back(L"43");
    _vec1.push_back(L"FT_Common.cff_op_max"); _vec2.push_back(L"59");
    _vec1.push_back(L"FT_Common.cff_op_mul"); _vec2.push_back(L"32");
    _vec1.push_back(L"FT_Common.cff_op_neg"); _vec2.push_back(L"30");
    _vec1.push_back(L"FT_Common.cff_op_not"); _vec2.push_back(L"46");
    _vec1.push_back(L"FT_Common.cff_op_or"); _vec2.push_back(L"45");
    _vec1.push_back(L"FT_Common.cff_op_pop"); _vec2.push_back(L"55");
    _vec1.push_back(L"FT_Common.cff_op_put"); _vec2.push_back(L"40");
    _vec1.push_back(L"FT_Common.cff_op_random"); _vec2.push_back(L"31");
    _vec1.push_back(L"FT_Common.cff_op_rcurveline"); _vec2.push_back(L"10");
    _vec1.push_back(L"FT_Common.cff_op_return"); _vec2.push_back(L"51");
    _vec1.push_back(L"FT_Common.cff_op_rlinecurve"); _vec2.push_back(L"11");
    _vec1.push_back(L"FT_Common.cff_op_rlineto"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.cff_op_rmoveto"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.cff_op_roll"); _vec2.push_back(L"38");
    _vec1.push_back(L"FT_Common.cff_op_rrcurveto"); _vec2.push_back(L"7");
    _vec1.push_back(L"FT_Common.cff_op_sbw"); _vec2.push_back(L"57");
    _vec1.push_back(L"FT_Common.cff_op_seac"); _vec2.push_back(L"56");
    _vec1.push_back(L"FT_Common.cff_op_setcurrentpoint"); _vec2.push_back(L"58");
    _vec1.push_back(L"FT_Common.cff_op_sqrt"); _vec2.push_back(L"33");
    _vec1.push_back(L"FT_Common.cff_op_store"); _vec2.push_back(L"42");
    _vec1.push_back(L"FT_Common.cff_op_sub"); _vec2.push_back(L"28");
    _vec1.push_back(L"FT_Common.cff_op_unknown"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.cff_op_vhcurveto"); _vec2.push_back(L"12");
    _vec1.push_back(L"FT_Common.cff_op_vlineto"); _vec2.push_back(L"6");
    _vec1.push_back(L"FT_Common.cff_op_vmoveto"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.cff_op_vstemhm"); _vec2.push_back(L"22");
    _vec1.push_back(L"FT_Common.cff_op_vstem"); _vec2.push_back(L"20");
    _vec1.push_back(L"FT_Common.cff_op_vvcurveto"); _vec2.push_back(L"13");
    _vec1.push_back(L"FT_Common.m_c"); _vec2.push_back(L"127");
    _vec1.push_back(L"FT_Common.m_i"); _vec2.push_back(L"2147483647");
    _vec1.push_back(L"FT_Common.m_s"); _vec2.push_back(L"32767");
    _vec1.push_back(L"FT_Common.op_callothersubr"); _vec2.push_back(L"21");
    _vec1.push_back(L"FT_Common.op_callsubr"); _vec2.push_back(L"22");
    _vec1.push_back(L"FT_Common.op_closepath"); _vec2.push_back(L"5");
    _vec1.push_back(L"FT_Common.op_div"); _vec2.push_back(L"20");
    _vec1.push_back(L"FT_Common.op_dotsection"); _vec2.push_back(L"15");
    _vec1.push_back(L"FT_Common.op_endchar"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.op_hlineto"); _vec2.push_back(L"6");
    _vec1.push_back(L"FT_Common.op_hmoveto"); _vec2.push_back(L"7");
    _vec1.push_back(L"FT_Common.op_hsbw"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.op_hstem3"); _vec2.push_back(L"17");
    _vec1.push_back(L"FT_Common.op_hstem"); _vec2.push_back(L"16");
    _vec1.push_back(L"FT_Common.op_hvcurveto"); _vec2.push_back(L"8");
    _vec1.push_back(L"FT_Common.op_max"); _vec2.push_back(L"27");
    _vec1.push_back(L"FT_Common.op_none"); _vec2.push_back(L"0");
    _vec1.push_back(L"FT_Common.op_pop"); _vec2.push_back(L"23");
    _vec1.push_back(L"FT_Common.op_return"); _vec2.push_back(L"24");
    _vec1.push_back(L"FT_Common.op_rlineto"); _vec2.push_back(L"9");
    _vec1.push_back(L"FT_Common.op_rmoveto"); _vec2.push_back(L"10");
    _vec1.push_back(L"FT_Common.op_rrcurveto"); _vec2.push_back(L"11");
    _vec1.push_back(L"FT_Common.op_sbw"); _vec2.push_back(L"4");
    _vec1.push_back(L"FT_Common.op_seac"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.op_setcurrentpoint"); _vec2.push_back(L"25");
    _vec1.push_back(L"FT_Common.op_unknown15"); _vec2.push_back(L"26");
    _vec1.push_back(L"FT_Common.op_vhcurveto"); _vec2.push_back(L"12");
    _vec1.push_back(L"FT_Common.op_vlineto"); _vec2.push_back(L"13");
    _vec1.push_back(L"FT_Common.op_vmoveto"); _vec2.push_back(L"14");
    _vec1.push_back(L"FT_Common.op_vstem3"); _vec2.push_back(L"19");
    _vec1.push_back(L"FT_Common.op_vstem"); _vec2.push_back(L"18");
    _vec1.push_back(L"FT_Common.tt_coderange_cvt"); _vec2.push_back(L"2");
    _vec1.push_back(L"FT_Common.tt_coderange_font"); _vec2.push_back(L"1");
    _vec1.push_back(L"FT_Common.tt_coderange_glyph"); _vec2.push_back(L"3");
    _vec1.push_back(L"FT_Common.tt_coderange_none"); _vec2.push_back(L"0");
}

void string_replace(std::wstring& text, const std::wstring& replaceFrom, const std::wstring& replaceTo)
{
    size_t posn = 0;
    while (std::wstring::npos != (posn = text.find(replaceFrom, posn)))
    {
        text.replace(posn, replaceFrom.length(), replaceTo);
        posn += replaceTo.length();
    }
}

void CorrectScript(std::wstring& sData, std::vector<std::wstring>& _vec1, std::vector<std::wstring>& _vec2)
{
    std::vector<std::wstring>::iterator i = _vec1.begin();
    std::vector<std::wstring>::iterator j = _vec2.begin();
    for (; i != _vec1.end(); i++, j++)
    {
        string_replace(sData, *i, *j);
    }
}

int main()
{
    std::wstring sBasePath = NSFile::GetProcessDirectory() + L"/../../Freetype/";

    // FILES
    std::vector<std::wstring> arFiles;
    arFiles.push_back(sBasePath + L"config.js");
    arFiles.push_back(sBasePath + L"services.js");
    arFiles.push_back(sBasePath + L"base.js");

    arFiles.push_back(sBasePath + L"modules/psnames.js");
    arFiles.push_back(sBasePath + L"modules/psaux.js");
    arFiles.push_back(sBasePath + L"modules/sfnt.js");
    arFiles.push_back(sBasePath + L"modules/render.js");

    arFiles.push_back(sBasePath + L"drivers/ttinterp.js");
    arFiles.push_back(sBasePath + L"drivers/truetype.js");
    arFiles.push_back(sBasePath + L"drivers/cff.js");
    arFiles.push_back(sBasePath + L"drivers/t1.js");

    arFiles.push_back(sBasePath + L"freetype.js");

    // CONFIG MAP
    std::vector<std::wstring> _vec1;
    std::vector<std::wstring> _vec2;
    GetConfigMap(_vec1, _vec2);

    // READ
    std::wstring sOutput = L"\"use strict\";\r\n\r\n";
    for (std::vector<std::wstring>::iterator i = arFiles.begin(); i != arFiles.end(); i++)
    {
        std::wstring sFileInput = *i;

        std::wstring sData = L"";
        NSFile::CFileBinary::ReadAllTextUtf8(sFileInput, sData);

        if (sFileInput.find(L"config.js") != std::wstring::npos)
        {
            std::wstring s0 = L"function _FT_Common()";
            std::wstring::size_type nPos0 = sData.find(s0);
            if (nPos0 != std::wstring::npos)
            {
                sData = sData.substr(nPos0);
            }

            std::wstring s1 = L"// GENERATOR_START_CONSTANTS";
            std::wstring s2 = L"// GENERATOR_END_CONSTANTS";

            std::wstring::size_type nPos1 = sData.find(s1);
            std::wstring::size_type nPos2 = sData.find(s2);

            if (nPos1 != std::wstring::npos && nPos2 != std::wstring::npos)
            {
                std::wstring sRes = sData.substr(0, nPos1) + sData.substr(nPos2 + s2.length());
                sData = sRes;
            }
        }

        CorrectScript(sData, _vec1, _vec2);

        sOutput += sData;
        sOutput += L"\n";
    }

    NSFile::CFileBinary::SaveToFile(sBasePath + L"../../font_engine.js", sOutput);

    return 0;
}

